<a href="https://colab.research.google.com/github/NIMALKANNAN/global-_let.ipynb/blob/main/Cross_Market_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  CRYPTO PROJECT 1

In [1]:
import requests

all_data = []

for page_num in range(1, 6):
    url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page={page_num}&sparkline=false"

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        all_data.extend(data)

In [2]:
import pandas as pd

df = pd.DataFrame(all_data)

df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,6.025146e+06,120815898744084,1,120815898744084,1.921319e+12,6.080190e+06,...,2.005269e+07,2.100000e+07,11187013.00,-46.14160,2025-10-06T18:57:42.558Z,3993.420000,1.507769e+05,2013-07-05T00:00:00.000Z,None,2026-07-06T04:17:11.920Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1.693980e+05,20444101093832,2,20444101093832,9.735510e+11,1.714460e+05,...,1.206832e+08,NaN,431946.00,-60.78246,2025-08-24T19:21:03.333Z,28.130000,6.020720e+05,2015-10-20T00:00:00.000Z,"{'times': 36.588838204296565, 'currency': 'btc...",2026-07-06T04:17:12.318Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,9.514000e+01,17538446131551,3,18058596575904,3.435629e+12,9.539000e+01,...,1.898014e+11,NaN,105.52,-9.81118,2025-01-25T16:51:57.989Z,36.860000,1.581855e+02,2015-03-02T00:00:00.000Z,None,2026-07-06T04:17:14.073Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5.565000e+04,7500511797301,4,7500511797301,7.633764e+10,5.649600e+04,...,1.347824e+08,2.000000e+08,121422.00,-54.16798,2025-10-13T08:41:24.131Z,2.580000,2.152929e+06,2017-10-19T00:00:00.000Z,None,2026-07-06T04:17:11.707Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,9.522000e+01,6931212082568,5,6940124781802,6.397840e+11,9.544000e+01,...,7.288145e+10,NaN,96.98,-1.78532,2026-05-20T14:19:58.071Z,65.310000,4.584493e+01,2021-05-19T13:14:05.611Z,None,2026-07-06T04:17:01.848Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,fartboy,$fartboy,Fartboy,https://coin-images.coingecko.com/coins/images...,8.192510e-01,818748565,1248,818748565,4.582649e+07,8.532460e-01,...,9.993869e+08,9.994405e+08,16.90,-95.16728,2025-02-12T21:45:25.974Z,0.620216,3.166843e+01,2026-02-05T15:31:35.053Z,None,2026-07-06T04:17:37.671Z
1246,bobo-coin-2,bobo,Bobo,https://coin-images.coingecko.com/coins/images...,8.176760e-01,817822934,1245,817822934,4.851703e+07,8.506960e-01,...,9.999989e+08,NaN,2.27,-63.98290,2026-05-10T09:55:26.125Z,0.648082,2.625735e+01,2026-06-05T07:25:15.391Z,None,2026-07-06T04:17:45.142Z
1247,midas-re7-ethereum,mre7eth,Midas Re7 Ethereum,https://coin-images.coingecko.com/coins/images...,1.704840e+05,815484361,1249,815484361,NaN,1.722100e+05,...,4.783344e+03,NaN,228779.00,-25.50992,2026-05-06T11:25:10.570Z,94.900000,1.794689e+05,2026-04-30T19:25:08.336Z,None,2026-07-06T04:15:43.073Z
1248,sandisk-ondo-tokenized,sndkon,SanDisk (Ondo Tokenized),https://coin-images.coingecko.com/coins/images...,1.742730e+05,815435547,1247,815435547,1.333260e+08,1.810190e+05,...,4.679072e+03,NaN,223407.00,-21.76156,2026-06-25T20:10:21.157Z,52284.000000,2.343080e+02,2026-03-30T23:54:37.586Z,None,2026-07-06T04:17:48.049Z
1249,stader,sd,Stader,https://coin-images.coingecko.com/coins/images...,1.133000e+01,814939545,1250,1360184890,1.720566e+07,1.158000e+01,...,1.200000e+08,1.500000e+08,2304.28,-99.50752,2022-03-15T14:33:38.024Z,10.540000,7.623370e+00,2026-07-01T07:46:29.847Z,None,2026-07-06T04:17:48.819Z

In [3]:
display(df)

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,6.025146e+06,120815898744084,1,120815898744084,1.921319e+12,6.080190e+06,...,2.005269e+07,2.100000e+07,11187013.00,-46.14160,2025-10-06T18:57:42.558Z,3993.420000,1.507769e+05,2013-07-05T00:00:00.000Z,None,2026-07-06T04:17:11.920Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1.693980e+05,20444101093832,2,20444101093832,9.735510e+11,1.714460e+05,...,1.206832e+08,NaN,431946.00,-60.78246,2025-08-24T19:21:03.333Z,28.130000,6.020720e+05,2015-10-20T00:00:00.000Z,"{'times': 36.588838204296565, 'currency': 'btc...",2026-07-06T04:17:12.318Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,9.514000e+01,17538446131551,3,18058596575904,3.435629e+12,9.539000e+01,...,1.898014e+11,NaN,105.52,-9.81118,2025-01-25T16:51:57.989Z,36.860000,1.581855e+02,2015-03-02T00:00:00.000Z,None,2026-07-06T04:17:14.073Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5.565000e+04,7500511797301,4,7500511797301,7.633764e+10,5.649600e+04,...,1.347824e+08,2.000000e+08,121422.00,-54.16798,2025-10-13T08:41:24.131Z,2.580000,2.152929e+06,2017-10-19T00:00:00.000Z,None,2026-07-06T04:17:11.707Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,9.522000e+01,6931212082568,5,6940124781802,6.397840e+11,9.544000e+01,...,7.288145e+10,NaN,96.98,-1.78532,2026-05-20T14:19:58.071Z,65.310000,4.584493e+01,2021-05-19T13:14:05.611Z,None,2026-07-06T04:17:01.848Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,fartboy,$fartboy,Fartboy,https://coin-images.coingecko.com/coins/images...,8.192510e-01,818748565,1248,818748565,4.582649e+07,8.532460e-01,...,9.993869e+08,9.994405e+08,16.90,-95.16728,2025-02-12T21:45:25.974Z,0.620216,3.166843e+01,2026-02-05T15:31:35.053Z,None,2026-07-06T04:17:37.671Z
1246,bobo-coin-2,bobo,Bobo,https://coin-images.coingecko.com/coins/images...,8.176760e-01,817822934,1245,817822934,4.851703e+07,8.506960e-01,...,9.999989e+08,NaN,2.27,-63.98290,2026-05-10T09:55:26.125Z,0.648082,2.625735e+01,2026-06-05T07:25:15.391Z,None,2026-07-06T04:17:45.142Z
1247,midas-re7-ethereum,mre7eth,Midas Re7 Ethereum,https://coin-images.coingecko.com/coins/images...,1.704840e+05,815484361,1249,815484361,NaN,1.722100e+05,...,4.783344e+03,NaN,228779.00,-25.50992,2026-05-06T11:25:10.570Z,94.900000,1.794689e+05,2026-04-30T19:25:08.336Z,None,2026-07-06T04:15:43.073Z
1248,sandisk-ondo-tokenized,sndkon,SanDisk (Ondo Tokenized),https://coin-images.coingecko.com/coins/images...,1.742730e+05,815435547,1247,815435547,1.333260e+08,1.810190e+05,...,4.679072e+03,NaN,223407.00,-21.76156,2026-06-25T20:10:21.157Z,52284.000000,2.343080e+02,2026-03-30T23:54:37.586Z,None,2026-07-06T04:17:48.049Z
1249,stader,sd,Stader,https://coin-images.coingecko.com/coins/images...,1.133000e+01,814939545,1250,1360184890,1.720566e+07,1.158000e+01,...,1.200000e+08,1.500000e+08,2304.28,-99.50752,2022-03-15T14:33:38.024Z,10.540000,7.623370e+00,2026-07-01T07:46:29.847Z,None,2026-07-06T04:17:48.819Z

In [4]:
import pandas as pd


df["last_updated"] = pd.to_datetime(df["last_updated"])


df["last_updated_date"] = df["last_updated"].dt.date

TOP THREE **COIN**

In [5]:
import requests
import pandas as pd
coin_id = "bitcoin"
url=f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"
response = requests.get(url)
response.json()

{'prices': [[1751846400000, 9337523.923073687],
  [1751932800000, 9302203.177316865],
  [1752019200000, 9338122.035800587],
  [1752105600000, 9541743.483380785],
  [1752192000000, 9934947.612549465],
  [1752278400000, 10091339.413757524],
  [1752364800000, 10078287.164944079],
  [1752451200000, 10222853.345055208],
  [1752537600000, 10301939.218478084],
  [1752624000000, 10119542.204331392],
  [1752710400000, 10198739.393321177],
  [1752796800000, 10277885.47839658],
  [1752883200000, 10164069.670952292],
  [1752969600000, 10156547.547410768],
  [1753056000000, 10101549.352407157],
  [1753142400000, 10136533.758092493],
  [1753228800000, 10357349.26643955],
  [1753315200000, 10249425.74900696],
  [1753401600000, 10229427.683390176],
  [1753488000000, 10168020.4311719],
  [1753574400000, 10203795.311577797],
  [1753660800000, 10330494.375551593],
  [1753747200000, 10240072.841855934],
  [1753833600000, 10260715.669243045],
  [1753920000000, 10330510.927890545],
  [1754006400000, 10122552.718401065],
  [1754092800000, 9870309.502282668],
  [1754179200000, 9811174.470132805],
  [1754265600000, 9963363.104407016],
  [1754352000000, 10119947.866363142],
  [1754438400000, 10011721.5506572],
  [1754524800000, 10094655.435390146],
  [1754611200000, 10270107.263258504],
  [1754697600000, 10236807.855788205],
  [1754784000000, 10220759.730383817],
  [1754870400000, 10434491.300112702],
  [1754956800000, 10412275.449238887],
  [1755043200000, 10529495.638104321],
  [1755129600000, 10805439.78369676],
  [1755216000000, 10383230.847886154],
  [1755302400000, 10268856.947554458],
  [1755388800000, 10282983.838569582],
  [1755475200000, 10286533.101169772],
  [1755561600000, 10148644.242275473],
  [1755648000000, 9819786.419050021],
  [1755734400000, 9942066.543754837],
  [1755820800000, 9813063.27750558],
  [1755907200000, 10203164.21582744],
  [1755993600000, 10074416.19618185],
  [1756080000000, 9903221.35080575],
  [1756166400000, 9653212.189243559],
  [1756252800000, 9801777.668906499],
  [1756339200000, 9749130.25886824],
  [1756425600000, 9856302.06893481],
  [1756512000000, 9564432.013993934],
  [1756598400000, 9591794.692119835],
  [1756684800000, 9545191.818462053],
  [1756771200000, 9606486.0790093],
  [1756857600000, 9784574.242949013],
  [1756944000000, 9838796.609221794],
  [1757030400000, 9765163.284050079],
  [1757116800000, 9759026.631183332],
  [1757203200000, 9718962.630296323],
  [1757289600000, 9800346.003033817],
  [1757376000000, 9856054.84901548],
  [1757462400000, 9840553.151484529],
  [1757548800000, 10035954.764445597],
  [1757635200000, 10195205.098488238],
  [1757721600000, 10254357.380846838],
  [1757808000000, 10237593.3071353],
  [1757894400000, 10184894.127284445],
  [1757980800000, 10169238.650025213],
  [1758067200000, 10261685.530263504],
  [1758153600000, 10237752.888404036],
  [1758240000000, 10333070.25718556],
  [1758326400000, 10189201.725638028],
  [1758412800000, 10194461.688819751],
  [1758499200000, 10158260.693491202],
  [1758585600000, 9951646.271657305],
  [1758672000000, 9948492.512889242],
  [1758758400000, 10060469.351465985],
  [1758844800000, 9673068.167457229],
  [1758931200000, 9728251.057537576],
  [1759017600000, 9723915.967631772],
  [1759104000000, 9944472.608696878],
  [1759190400000, 10139763.924082505],
  [1759276800000, 10130020.723922314],
  [1759363200000, 10509252.859358784],
  [1759449600000, 10700725.995237181],
  [1759536000000, 10847910.013598107],
  [1759622400000, 10859533.642673422],
  [1759708800000, 10959365.064936124],
  [1759795200000, 11070472.246732509],
  [1759881600000, 10783920.730192943],
  [1759968000000, 10949945.97908964],
  [1760054400000, 10814774.599012492],
  [1760140800000, 10047260.111235712],
  [1760227200000, 9838358.210748602],
  [1760313600000, 10223942.881584922],
  [1760400000000, 10216224.051870666],
  [1760486400000, 10046351.075825775],
  [1760572800000, 9721344.884648668],
  [1760659200000, 9509774.024195194],
  [1760745600000, 9369768.130232994],
  [1760832000000, 9432476.848616607],
  [1760918400000, 9558930.877185136],
  [1761004800000, 9720308.914971137],
  [1761091200000, 9549158.301143315],
  [1761177600000, 9442499.946295625],
  [1761264000000, 9659976.397607893],
  [1761350400000, 9747832.72977752],
  [1761436800000, 9802501.15016422],
  [1761523200000, 10055171.794296525],
  [1761609600000, 10073474.454011032],
  [1761696000000, 9965129.220872145],
  [1761782400000, 9722166.86543983],
  [1761868800000, 9593893.17104472],
  [1761955200000, 9734748.91964181],
  [1762041600000, 9765788.362963019],
  [1762128000000, 9824421.072227614],
  [1762214400000, 9450928.858755054],
  [1762300800000, 9018317.599498693],
  [1762387200000, 9199126.082980732],
  [1762473600000, 8984607.813501872],
  [1762560000000, 9167651.236387476],
  [1762646400000, 9069592.039128657],
  [1762732800000, 9283589.00601575],
  [1762819200000, 9394913.182233905],
  [1762905600000, 9108594.696793688],
  [1762992000000, 8994239.327086337],
  [1763078400000, 8857694.85444411],
  [1763164800000, 8376936.116014769],
  [1763251200000, 8470582.749251666],
  [1763337600000, 8373085.239387692],
  [1763424000000, 8157780.455111292],
  [1763510400000, 8219844.429070548],
  [1763596800000, 8084502.70583037],
  [1763683200000, 7685198.360480496],
  [1763769600000, 7622398.708162882],
  [1763856000000, 7591078.566298594],
  [1763942400000, 7778520.446850556],
  [1764028800000, 7865475.253834086],
  [1764115200000, 7783791.323601658],
  [1764201600000, 8066930.863801428],
  [1764288000000, 8157156.351483771],
  [1764374400000, 8126220.637986011],
  [1764460800000, 8116488.479072998],
  [1764547200000, 8078246.317717989],
  [1764633600000, 7731939.31508293],
  [1764720000000, 8213485.439946512],
  [1764806400000, 8441734.894689914],
  [1764892800000, 8277612.193785475],
  [1764979200000, 8033337.656068311],
  [1765065600000, 8028324.929700683],
  [1765152000000, 8110183.521497487],
  [1765238400000, 8167418.75650716],
  [1765324800000, 8337407.11660591],
  [1765411200000, 8261440.281355997],
  [1765497600000, 8347818.307928058],
  [1765584000000, 8175319.49414227],
  [1765670400000, 8175924.735194205],
  [1765756800000, 7992348.231966222],
  [1765843200000, 7844409.288926788],
  [1765929600000, 7987315.985984798],
  [1766016000000, 7781471.915537124],
  [1766102400000, 7712879.171308659],
  [1766188800000, 7892110.371399885],
  [1766275200000, 7913974.621357582],
  [1766361600000, 7933999.65474005],
  [1766448000000, 7929162.75966298],
  [1766534400000, 7820620.968822208],
  [1766620800000, 7872946.774052088],
  [1766707200000, 7860175.221034703],
  [1766793600000, 7838865.798860937],
  [1766880000000, 7886342.002067149],
  [1766966400000, 7887770.596681177],
  [1767052800000, 7835388.056690424],
  [1767139200000, 7936951.056508718],
  [1767225600000, 7875103.91153735],
  [1767312000000, 7982611.090931888],
  [1767398400000, 8094664.567193232],
  [1767484800000, 8154755.980058913],
  [1767571200000, 8224912.970329631],
  [1767657600000, 8475311.204337161],
  [1767744000000, 8443838.294347357],
  [1767830400000, 8200790.873528976],
  [1767916800000, 8179932.125614385],
  [1768003200000, 8169727.593041189],
  [1768089600000, 8164051.8328820085],
  [1768176000000, 8196362.9552232],
  [1768262400000, 8214254.506811856],
  [1768348800000, 8600260.479528198],
  [1768435200000, 8754772.557780331],
  [1768521600000, 8637202.771129187],
  [1768608000000, 8665871.041073622],
  [1768694400000, 8641731.269593248],
  [1768780800000, 8504968.615885023],
  [1768867200000, 8414003.970645163],
  [1768953600000, 8046939.8302773405],
  [1769040000000, 8179241.969294843],
  [1769126400000, 8189307.776814618],
  [1769212800000, 8190756.883147298],
  [1769299200000, 8167427.829795334],
  [1769385600000, 7931480.8104405],
  [1769472000000, 8098992.121060789],
  [1769558400000, 8165356.488930265],
  [1769644800000, 8206661.924142179],
  [1769731200000, 7762053.970031044],
  [1769817600000, 7714332.820802952],
  [1769904000000, 7217787.461780625],
  [1769990400000, 7055170.4747747015],
  [1770076800000, 7124353.514366637],
  [1770163200000, 6839512.652076184],
  [1770249600000, 6617843.606631121],
  [1770336000000, 5676634.189757013],
  [1770422400000, 6389223.0613750955],
  [1770508800000, 6278047.808376017],
  [1770595200000, 6388983.809905373],
  [1770681600000, 6363124.007122537],
  [1770768000000, 6230645.199778009],
  [1770854400000, 6073656.888033923],
  [1770940800000, 5993963.2553228345],
  [1771027200000, 6234117.350281114],
  [1771113600000, 6317657.207954805],
  [1771200000000, 6222983.54818252],
  [1771286400000, 6255749.578602175],
  [1771372800000, 6116329.755578176],
  [1771459200000, 6033801.7653913135],
  [1771545600000, 6092367.347486159],
  [1771632000000, 6166730.671036533],
  [1771718400000, 6167421.5569663085],
  [1771804800000, 6132044.38390857],
  [1771891200000, 5877904.816486458],
  [1771977600000, 5825506.041087636],
  [1772064000000, 6179906.746479165],
  [1772150400000, 6139221.658943246],
  [1772236800000, 6000769.898243445],
  [1772323200000, 6102895.493287365],
  [1772409600000, 5984275.487394328],
  [1772496000000, 6305544.630558076],
  [1772582400000, 6286193.4883730775],
  [1772668800000, 6694568.0647264635],
  [1772755200000, 6505413.051213356],
  [1772841600000, 6265583.842492761],
  [1772928000000, 6184943.552139279],
  [1773014400000, 6071162.609842083],
  [1773100800000, 6319544.712079575],
  [1773187200000, 6427459.132593709],
  [1773273600000, 6476952.781587672],
  [1773360000000, 6517601.8570237355],
  [1773446400000, 6571729.3213031115],
  [1773532800000, 6593624.616147389],
  [1773619200000, 6727548.65801573],
  [1773705600000, 6906940.623961062],
  [1773792000000, 6829860.404015485],
  [1773878400000, 6639390.135900453],
  [1773964800000, 6504037.303025701],
  [1774051200000, 6635372.108167125],
  [1774137600000, 6461678.631620447],
  [1774224000000, 6364717.089252187],
  [1774310400000, 6614293.785503927],
  [1774396800000, 6649392.307315811],
  [1774483200000, 6712173.7324164715],
  [1774569600000, 6487672.4747853875],
  [1774656000000, 6291490.149056623],
  [1774742400000, 6286074.723243884],
  [1774828800000, 6252812.76341992],
  [1774915200000, 6293233.346703139],
  [1775001600000, 6378628.7912758235],
  [1775088000000, 6307964.144411761],
  [1775174400000, 6219175.587858993],
  [1775260800000, 6209570.020236374],
  [1775347200000, 6257848.032767002],
  [1775433600000, 6414170.630916693],
  [1775520000000, 6401867.152927511],
  [1775606400000, 6683688.621062967],
  [1775692800000, 6562922.40461313],
  [1775779200000, 6636645.267469073],
  [1775865600000, 6794200.6216164315],
  [1775952000000, 6801700.513610883],
  [1776038400000, 6685979.115010805],
  [1776124800000, 7073662.431479191],
  [1776211200000, 6911131.07709397],
  [1776297600000, 6988481.301043976],
  [1776384000000, 6992493.008957324],
  [1776470400000, 7142282.9730217345],
  [1776556800000, 7012640.787487506],
  [1776643200000, 6839333.548077347],
  [1776729600000, 7065729.10911125],
  [1776816000000, 7148143.539554088],
  [1776902400000, 7334729.558793859],
  [1776988800000, 7365352.684706975],
  [1777075200000, 7284891.168464326],
  [1777161600000, 7301368.80155073],
  [1777248000000, 7412345.556328853],
  [1777334400000, 7291979.197798691],
  [1777420800000, 7225751.022576523],
  [1777507200000, 7192314.200703767],
  [1777593600000, 7228865.850329309],
  [1777680000000, 7417877.106798627],
  [1777766400000, 7465219.196657779],
  [1777852800000, 7456410.950895795],
  [1777939200000, 7603972.251116524],
  [1778025600000, 7697655.602279161],
  [1778112000000, 7698492.925461688],
  [1778198400000, 7542918.579516168],
  [1778284800000, 7571892.400148334],
  [1778371200000, 7618063.532725338],
  [1778457600000, 7756648.343564863],
  [1778544000000, 7795901.593467104],
  [1778630400000, 7697232.982407427],
  [1778716800000, 7586573.537859392],
  [1778803200000, 7757493.3873965945],
  [1778889600000, 7590843.949543865],
  [1778976000000, 7503070.600337917],
  [1779062400000, 7430585.916040752],
  [1779148800000, 7408220.505409941],
  [1779235200000, 7417123.901127137],
  [1779321600000, 7477092.237761773],
  [1779408000000, 7457952.876748778],
  [1779494400000, 7225168.156497625],
  [1779580800000, 7337622.852549568],
  [1779667200000, 7369287.471881351],
  [1779753600000, 7360618.568158094],
  [1779840000000, 7283830.127183205],
  [1779926400000, 7148305.685131139],
  [1780012800000, 7047782.6729114475],
  [1780099200000, 6972572.723842387],
  [1780185600000, 7011112.079392844],
  [1780272000000, 6992466.216201578],
  [1780358400000, 6818596.533222088],
  [1780444800000, 6365960.984692129],
  [1780531200000, 6156649.221559247],
  [1780617600000, 6121199.57188867],
  [1780704000000, 5810041.473310702],
  [1780790400000, 5804327.5167383235],
  [1780876800000, 6006055.783159577],
  [1780963200000, 6035878.76707067],
  [1781049600000, 5879771.036844346],
  [1781136000000, 5881423.498217684],
  [1781222400000, 6085790.7017320935],
  [1781308800000, 6054380.8972982885],
  [1781395200000, 6133795.721724234],
  [1781481600000, 6250059.076464356],
  [1781568000000, 6281482.562726693],
  [1781654400000, 6204053.777900177],
  [1781740800000, 6111070.771920747],
  [1781827200000, 5934017.047704595],
  [1781913600000, 5991275.243498097],
  [1782000000000, 6072230.915286874],
  [1782086400000, 5964696.9088890385],
  [1782172800000, 6056800.020760549],
  [1782259200000, 5963458.060073432],
  [1782345600000, 5752302.571712614],
  [1782432000000, 5636909.241663675],
  [1782518400000, 5657787.34857167],
  [1782604800000, 5656261.844258678],
  [1782691200000, 5625048.613700595],
  [1782777600000, 5702577.84692923],
  [1782864000000, 5542735.990392354],
  [1782950400000, 5723147.290773006],
  [1783036800000, 5873719.102036603],
  [1783123200000, 5971834.682148911],
  [1783209600000, 6007550.319658025],
  [1783296000000, 6050576.903586207],
  [1783311486000, 6025952.674578792]],
 'market_caps': [[1751846400000, 185655570923395.9],
  [1751932800000, 184993020620040.47],
  [1752019200000, 185732711341357.97],
  [1752105600000, 189862956245589.16],
  [1752192000000, 197472885391991.06],
  [1752278400000, 200727427668076.25],
  [1752364800000, 200459098474667.5],
  [1752451200000, 203315574509896.47],
  [1752537600000, 204934287036692.16],
  [1752624000000, 201329642820657.56],
  [1752710400000, 202964035111987.44],
  [1752796800000, 204467504015373.97],
  [1752883200000, 202194802954273.38],
  [1752969600000, 202042587795977.12],
  [1753056000000, 201050515863258.1],
  [1753142400000, 201670805141508.38],
  [1753228800000, 206145479119255.44],
  [1753315200000, 203895633737564.28],
  [1753401600000, 203523367873936.34],
  [1753488000000, 202325740297391.03],
  [1753574400000, 203017861799776.94],
  [1753660800000, 205584489488322.06],
  [1753747200000, 203882439269756.53],
  [1753833600000, 204174804126429.94],
  [1753920000000, 205475160109208.53],
  [1754006400000, 201418598950867.1],
  [1754092800000, 196440187132600.3],
  [1754179200000, 195292182084368.75],
  [1754265600000, 198291846642595.6],
  [1754352000000, 201486748276313.56],
  [1754438400000, 199270892939290.16],
  [1754524800000, 200914827967105.34],
  [1754611200000, 204393470495470.22],
  [1754697600000, 203793891638644.78],
  [1754784000000, 203416381978669.38],
  [1754870400000, 207706349052045.0],
  [1754956800000, 207244778123923.12],
  [1755043200000, 209609141993351.22],
  [1755129600000, 215031000029612.2],
  [1755216000000, 206957101711685.75],
  [1755302400000, 204370252307073.22],
  [1755388800000, 204735653506412.72],
  [1755475200000, 204837292551727.03],
  [1755561600000, 201962766971242.97],
  [1755648000000, 195515560635649.2],
  [1755734400000, 197920965863668.06],
  [1755820800000, 195373793285328.53],
  [1755907200000, 203145427117689.78],
  [1755993600000, 200578902575120.06],
  [1756080000000, 197337157539184.9],
  [1756166400000, 192253566119456.97],
  [1756252800000, 195174193600792.6],
  [1756339200000, 194192949775483.56],
  [1756425600000, 196154977042293.1],
  [1756512000000, 190466259990984.72],
  [1756598400000, 191000581742192.47],
  [1756684800000, 190077443129645.88],
  [1756771200000, 191324225295333.6],
  [1756857600000, 194705593834920.22],
  [1756944000000, 195995207744701.4],
  [1757030400000, 194382283026013.5],
  [1757116800000, 194369381960638.12],
  [1757203200000, 193594824226368.0],
  [1757289600000, 195224232003967.34],
  [1757376000000, 196352227628354.12],
  [1757462400000, 196025093616288.06],
  [1757548800000, 199903261160101.6],
  [1757635200000, 202994782144656.53],
  [1757721600000, 204305404171092.7],
  [1757808000000, 203935682408182.56],
  [1757894400000, 202814048399023.3],
  [1757980800000, 202506403484339.1],
  [1758067200000, 204361008660291.88],
  [1758153600000, 204092626825506.03],
  [1758240000000, 205849496825239.38],
  [1758326400000, 202934125316144.34],
  [1758412800000, 203101768233452.88],
  [1758499200000, 202393681690129.25],
  [1758585600000, 198325980390320.84],
  [1758672000000, 198281600093060.1],
  [1758758400000, 200439411695619.1],
  [1758844800000, 192811945929511.0],
  [1758931200000, 193825725243377.5],
  [1759017600000, 193778390136544.84],
  [1759104000000, 198264048840800.84],
  [1759190400000, 202101361620363.16],
  [1759276800000, 201858858923047.34],
  [1759363200000, 209254296833174.56],
  [1759449600000, 212886867518904.16],
  [1759536000000, 216244223708841.97],
  [1759622400000, 216410990916525.38],
  [1759708800000, 218397392732507.6],
  [1759795200000, 220576680476958.94],
  [1759881600000, 214929720047457.5],
  [1759968000000, 218284637522631.06],
  [1760054400000, 215347121833658.2],
  [1760140800000, 201089430996440.47],
  [1760227200000, 196264981165620.7],
  [1760313600000, 203674096199773.7],
  [1760400000000, 203652208525284.38],
  [1760486400000, 200430866162162.3],
  [1760572800000, 193862163402547.8],
  [1760659200000, 189617377252504.53],
  [1760745600000, 186880034967913.84],
  [1760832000000, 187985423043742.34],
  [1760918400000, 190557773399386.5],
  [1761004800000, 193826164365049.7],
  [1761091200000, 190339599421872.66],
  [1761177600000, 188271325012245.56],
  [1761264000000, 192579058179575.6],
  [1761350400000, 194372675862396.5],
  [1761436800000, 195387408897753.5],
  [1761523200000, 200591444058607.28],
  [1761609600000, 200814809205289.5],
  [1761696000000, 198861127121243.06],
  [1761782400000, 193898706517251.9],
  [1761868800000, 191256837648652.6],
  [1761955200000, 194136677139361.38],
  [1762041600000, 194764805087231.2],
  [1762128000000, 195498057427515.34],
  [1762214400000, 188419014058022.22],
  [1762300800000, 179779451550662.6],
  [1762387200000, 183578822350974.2],
  [1762473600000, 179044377854927.3],
  [1762560000000, 182918569470071.84],
  [1762646400000, 180876981767646.8],
  [1762732800000, 184982516291615.94],
  [1762819200000, 187416193618283.44],
  [1762905600000, 181641130738594.62],
  [1762992000000, 179473072261799.56],
  [1763078400000, 177292442139529.44],
  [1763164800000, 167775697407740.66],
  [1763251200000, 168974250569731.53],
  [1763337600000, 167019517950316.3],
  [1763424000000, 162687992182158.4],
  [1763510400000, 163939688566164.8],
  [1763596800000, 161052535799302.25],
  [1763683200000, 153549563596537.7],
  [1763769600000, 152151141809995.97],
  [1763856000000, 151544044538742.12],
  [1763942400000, 155261744292657.5],
  [1764028800000, 157040003777871.62],
  [1764115200000, 155315312055547.7],
  [1764201600000, 161067096547133.2],
  [1764288000000, 162803299155062.88],
  [1764374400000, 162159190667832.88],
  [1764460800000, 161967220109726.78],
  [1764547200000, 161537520073734.03],
  [1764633600000, 154452151784487.53],
  [1764720000000, 164085243698401.44],
  [1764806400000, 168443528923744.7],
  [1764892800000, 165242591304162.88],
  [1764979200000, 160366058178078.4],
  [1765065600000, 160233612253860.62],
  [1765152000000, 161879718559142.9],

In [10]:
import requests
import pandas as pd

coin_id = "bitcoin"

url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"

response = requests.get(url)
data = response.json()

# Check if 'prices' key exists before trying to access it
if 'prices' in data:
    prices = data['prices']

    df = pd.DataFrame(prices, columns=['timestamp', 'price_usd'])


    df['date'] = pd.to_datetime(df['timestamp'], unit='ms').dt.date


    df['coin_id'] = coin_id


    df = df[['coin_id', 'date', 'price_usd']]

    print(df.head())
else:
    print(f"Error: Could not retrieve price data. API response: {data.get('status', 'No status info.')}")

   coin_id        date      price_usd
0  bitcoin  2025-07-07  109215.197718
1  bitcoin  2025-07-08  108300.716758
2  bitcoin  2025-07-09  108953.191877
3  bitcoin  2025-07-10  111327.530542
4  bitcoin  2025-07-11  115879.650301

In [11]:
import requests
import pandas as pd
coin_id = "ethereum"
url=f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"
response = requests.get(url)
response.json()

{'prices': [[1751846400000, 219842.28509645213],
  [1751932800000, 218478.50703220506],
  [1752019200000, 224192.01293457407],
  [1752105600000, 237634.3285912139],
  [1752192000000, 252785.18261104374],
  [1752278400000, 253963.71411998925],
  [1752364800000, 252599.85968309751],
  [1752451200000, 255256.0749124428],
  [1752537600000, 258953.02296009834],
  [1752624000000, 269423.17285168904],
  [1752710400000, 289273.06195820443],
  [1752796800000, 299604.7001320289],
  [1752883200000, 305580.9799247014],
  [1752969600000, 309629.88231970003],
  [1753056000000, 323799.5635112756],
  [1753142400000, 324888.02667051577],
  [1753228800000, 323522.2855073287],
  [1753315200000, 313632.80993368995],
  [1753401600000, 320521.28663827025],
  [1753488000000, 322067.53188592376],
  [1753574400000, 323729.6744159729],
  [1753660800000, 334271.3356334813],
  [1753747200000, 328567.3072022601],
  [1753833600000, 329848.44489638496],
  [1753920000000, 333798.49786685634],
  [1754006400000, 323419.73918441863],
  [1754092800000, 303617.9116663577],
  [1754179200000, 296151.6805356246],
  [1754265600000, 305147.6597239278],
  [1754352000000, 326586.85608261486],
  [1754438400000, 316895.55183794844],
  [1754524800000, 323322.0010279766],
  [1754611200000, 341975.0422938313],
  [1754697600000, 352049.4403810017],
  [1754784000000, 374193.3376648639],
  [1754870400000, 372140.5970629246],
  [1754956800000, 370718.8174494866],
  [1755043200000, 403547.06190802733],
  [1755129600000, 416582.6051270567],
  [1755216000000, 399375.2127189976],
  [1755302400000, 387732.95356370165],
  [1755388800000, 387408.6664674909],
  [1755475200000, 392681.4189909559],
  [1755561600000, 376878.0982824829],
  [1755648000000, 354772.70430919825],
  [1755734400000, 376832.66666282027],
  [1755820800000, 368766.6639472321],
  [1755907200000, 421737.4738716338],
  [1755993600000, 416904.49092835333],
  [1756080000000, 417273.9071184703],
  [1756166400000, 383869.2304155191],
  [1756252800000, 403346.84673449927],
  [1756339200000, 394479.82107990474],
  [1756425600000, 394824.62858350464],
  [1756512000000, 384794.36172029114],
  [1756598400000, 385618.86285304534],
  [1756684800000, 386992.0744205619],
  [1756771200000, 378688.487081064],
  [1756857600000, 380669.0608269572],
  [1756944000000, 391914.25736500154],
  [1757030400000, 379062.50711160863],
  [1757116800000, 379789.69451721257],
  [1757203200000, 376830.61714539555],
  [1757289600000, 379557.7315665512],
  [1757376000000, 379169.3803941581],
  [1757462400000, 380163.9598970403],
  [1757548800000, 382811.6356012148],
  [1757635200000, 393614.0739117057],
  [1757721600000, 415686.0060768963],
  [1757808000000, 412052.856085073],
  [1757894400000, 406940.596240047],
  [1757980800000, 398693.42995223537],
  [1758067200000, 395856.797622927],
  [1758153600000, 403666.7568900215],
  [1758240000000, 404926.98327490315],
  [1758326400000, 393846.3358485685],
  [1758412800000, 394843.6203459821],
  [1758499200000, 392295.47524281475],
  [1758585600000, 370875.27142150694],
  [1758672000000, 369992.0919011612],
  [1758758400000, 368312.96560615575],
  [1758844800000, 342937.4440185811],
  [1758931200000, 357978.55612770614],
  [1759017600000, 356321.1005771281],
  [1759104000000, 367286.12298418215],
  [1759190400000, 373944.85329388455],
  [1759276800000, 368177.3713848715],
  [1759363200000, 385235.77973544877],
  [1759449600000, 397823.05193989933],
  [1759536000000, 400707.46142882656],
  [1759622400000, 398218.8935895547],
  [1759708800000, 400668.6421398132],
  [1759795200000, 416041.06085392536],
  [1759881600000, 395289.8026309068],
  [1759968000000, 401911.0484708849],
  [1760054400000, 388222.87205311254],
  [1760140800000, 340432.9353676543],
  [1760227200000, 332747.98798714374],
  [1760313600000, 369207.3362657844],
  [1760400000000, 376492.3574048653],
  [1760486400000, 366574.05838423775],
  [1760572800000, 349761.3884710538],
  [1760659200000, 342302.33220614656],
  [1760745600000, 337247.7588866496],
  [1760832000000, 342375.6803081046],
  [1760918400000, 350696.6804336402],
  [1761004800000, 349657.073530753],
  [1761091200000, 341303.9842640361],
  [1761177600000, 333571.21535914514],
  [1761264000000, 338462.9290819708],
  [1761350400000, 345416.6546043208],
  [1761436800000, 347083.5922685809],
  [1761523200000, 365539.5621120337],
  [1761609600000, 363758.94232227415],
  [1761696000000, 351342.5325721324],
  [1761782400000, 344315.5289450759],
  [1761868800000, 337015.4990615576],
  [1761955200000, 341801.10296794504],
  [1762041600000, 343730.3913686987],
  [1762128000000, 347169.85800323385],
  [1762214400000, 319468.25832003524],
  [1762300800000, 292527.2014230804],
  [1762387200000, 303546.1807953054],
  [1762473600000, 293412.52766766545],
  [1762560000000, 304507.99491275364],
  [1762646400000, 301591.6290594234],
  [1762732800000, 317071.7291616941],
  [1762819200000, 316207.1597353334],
  [1762905600000, 302271.19106009],
  [1762992000000, 302072.2252489844],
  [1763078400000, 287385.51825001417],
  [1763164800000, 275511.26516527805],
  [1763251200000, 281155.6844835739],
  [1763337600000, 275080.20597856207],
  [1763424000000, 267796.5731112152],
  [1763510400000, 276052.04898099863],
  [1763596800000, 267032.830083096],
  [1763683200000, 251183.08126814634],
  [1763769600000, 247777.39778764817],
  [1763856000000, 248183.09115512334],
  [1763942400000, 250950.12836319354],
  [1764028800000, 263283.40358322934],
  [1764115200000, 263444.9399900479],
  [1764201600000, 269938.1970950932],
  [1764288000000, 269490.2527975858],
  [1764374400000, 271004.1486761167],
  [1764460800000, 267260.2384447111],
  [1764547200000, 267424.4592587914],
  [1764633600000, 250829.94408877468],
  [1764720000000, 269370.30418167287],
  [1764806400000, 288132.42535713845],
  [1764892800000, 281520.95159888716],
  [1764979200000, 271893.52182715805],
  [1765065600000, 273416.13820120675],
  [1765152000000, 274616.2375638853],
  [1765238400000, 281685.69218486216],
  [1765324800000, 298746.9630305986],
  [1765411200000, 298675.7147486205],
  [1765497600000, 292065.55714175856],
  [1765584000000, 279306.9974351619],
  [1765670400000, 282191.1596649078],
  [1765756800000, 277686.2575249929],
  [1765843200000, 269107.8224748998],
  [1765929600000, 269596.8374095658],
  [1766016000000, 255672.94816147196],
  [1766102400000, 255132.82641488407],
  [1766188800000, 266653.5750632806],
  [1766275200000, 266686.3060581252],
  [1766361600000, 268857.45721078233],
  [1766448000000, 269330.66898642445],
  [1766534400000, 265308.33057719615],
  [1766620800000, 264638.4624631536],
  [1766707200000, 261698.83888170918],
  [1766793600000, 262776.73658441985],
  [1766880000000, 264850.5744899021],
  [1766966400000, 264760.5504658988],
  [1767052800000, 263786.42273046816],
  [1767139200000, 266620.8671552428],
  [1767225600000, 266951.6312463789],
  [1767312000000, 269940.3569195695],
  [1767398400000, 281016.1719855551],
  [1767484800000, 281388.8695194364],
  [1767571200000, 282560.6030133936],
  [1767657600000, 291299.3568651643],
  [1767744000000, 297045.36579862604],
  [1767830400000, 284403.12191626645],
  [1767916800000, 279086.945835317],
  [1768003200000, 278309.6101406161],
  [1768089600000, 278294.1933407241],
  [1768176000000, 281519.50124331604],
  [1768262400000, 278535.9889192714],
  [1768348800000, 299728.9177688779],
  [1768435200000, 302917.5844429012],
  [1768521600000, 299838.3615803796],
  [1768608000000, 299041.3190188698],
  [1768694400000, 300496.6677650833],
  [1768780800000, 297943.7602436932],
  [1768867200000, 289592.03165583033],
  [1768953600000, 267489.81096221146],
  [1769040000000, 272419.05713641306],
  [1769126400000, 269940.0485702116],
  [1769212800000, 270322.79786255566],
  [1769299200000, 270125.836049164],
  [1769385600000, 257898.21011062048],
  [1769472000000, 268521.1124032741],
  [1769558400000, 276537.237355733],
  [1769644800000, 276752.68161058764],
  [1769731200000, 258717.1664228855],
  [1769817600000, 247763.65614624374],
  [1769904000000, 224065.64499097393],
  [1769990400000, 208098.68569226892],
  [1770076800000, 212055.7416695305],
  [1770163200000, 201371.05394647823],
  [1770249600000, 194638.91147198106],
  [1770336000000, 164424.8093049238],
  [1770422400000, 186695.3649137571],
  [1770508800000, 189440.9269478321],
  [1770595200000, 189754.81871261535],
  [1770681600000, 191035.83888725925],
  [1770768000000, 182890.5822309681],
  [1770854400000, 175976.56404532818],
  [1770940800000, 176214.23834483154],
  [1771027200000, 185411.2111430372],
  [1771113600000, 188855.60230133013],
  [1771200000000, 177856.25063894037],
  [1771286400000, 181624.1547003928],
  [1771372800000, 180528.32834312637],
  [1771459200000, 177478.4599141033],
  [1771545600000, 177249.2474816647],
  [1771632000000, 178533.39457288812],
  [1771718400000, 179064.34776215904],
  [1771804800000, 177305.13210485573],
  [1771891200000, 168724.9961412896],
  [1771977600000, 168454.26945512652],
  [1772064000000, 186740.27349943476],
  [1772150400000, 184470.53087042045],
  [1772236800000, 175906.3206947476],
  [1772323200000, 178968.6577342996],
  [1772409600000, 176523.67517814328],
  [1772496000000, 185826.30723370606],
  [1772582400000, 182403.7063918738],
  [1772668800000, 195838.5762971537],
  [1772755200000, 190414.48477250861],
  [1772841600000, 182113.64679332406],
  [1772928000000, 181094.53416839553],
  [1773014400000, 178231.25313766958],
  [1773100800000, 183916.21187136925],
  [1773187200000, 187187.4516331626],
  [1773273600000, 189229.2165179718],
  [1773360000000, 191849.4049405151],
  [1773446400000, 193822.53813563587],
  [1773532800000, 194109.35694618177],
  [1773619200000, 201326.8605615016],
  [1773705600000, 216935.79260143827],
  [1773792000000, 214165.15893144385],
  [1773878400000, 205303.8038714824],
  [1773964800000, 198966.16556431886],
  [1774051200000, 201919.60235025213],
  [1774137600000, 195358.5494385478],
  [1774224000000, 192599.90071599535],
  [1774310400000, 200734.57390458471],
  [1774396800000, 203248.10990075232],
  [1774483200000, 204093.18722240234],
  [1774569600000, 194215.1445198042],
  [1774656000000, 188960.00950780787],
  [1774742400000, 188879.4937558675],
  [1774828800000, 187970.26886850147],
  [1774915200000, 190952.5539750653],
  [1775001600000, 196773.65090822996],
  [1775088000000, 198168.419125506],
  [1775174400000, 191237.00984683796],
  [1775260800000, 190500.24725314407],
  [1775347200000, 192000.04588379155],
  [1775433600000, 196092.16885837808],
  [1775520000000, 195951.30882983957],
  [1775606400000, 208176.04167712756],
  [1775692800000, 202144.70913738868],
  [1775779200000, 202414.59656178358],
  [1775865600000, 209027.3392670983],
  [1775952000000, 212789.26863678455],
  [1776038400000, 207142.66003070216],
  [1776124800000, 225160.61977852663],
  [1776211200000, 216444.0966506261],
  [1776297600000, 220363.90092512764],
  [1776384000000, 218542.6162370739],
  [1776470400000, 224191.18021452706],
  [1776556800000, 217702.43848731273],
  [1776643200000, 209729.87382388298],
  [1776729600000, 215583.9382889891],
  [1776816000000, 217908.74029414722],
  [1776902400000, 223052.03703739005],
  [1776988800000, 219361.5025076131],
  [1777075200000, 217810.06654775635],
  [1777161600000, 218154.5858669989],
  [1777248000000, 223349.56012918853],
  [1777334400000, 216773.48412413293],
  [1777420800000, 216553.72585673918],
  [1777507200000, 213891.1914786866],
  [1777593600000, 213775.20801451607],
  [1777680000000, 217744.42364856272],
  [1777766400000, 219844.00541708147],
  [1777852800000, 220584.65644175006],
  [1777939200000, 223478.04574367165],
  [1778025600000, 224588.24323228054],
  [1778112000000, 222230.76757719123],
  [1778198400000, 215968.26071343615],
  [1778284800000, 217823.68325943328],
  [1778371200000, 219676.88930568274],
  [1778457600000, 223678.787602731],
  [1778544000000, 223178.60546508426],
  [1778630400000, 217548.032355043],
  [1778716800000, 216045.0623399608],
  [1778803200000, 218362.2577899985],
  [1778889600000, 213471.20427804557],
  [1778976000000, 209327.02352450276],
  [1779062400000, 204225.28201707866],
  [1779148800000, 204910.72818587456],
  [1779235200000, 203923.1368849217],
  [1779321600000, 205344.48039623885],
  [1779408000000, 205013.8783464013],
  [1779494400000, 197601.7554314198],
  [1779580800000, 202474.27891615097],
  [1779667200000, 200833.3043641476],
  [1779753600000, 201098.97530181444],
  [1779840000000, 198928.96827033538],
  [1779926400000, 194444.76203923384],
  [1780012800000, 192397.25310019453],
  [1780099200000, 191195.16218819868],
  [1780185600000, 191952.02233064343],
  [1780272000000, 190407.1765461077],
  [1780358400000, 191424.83778170744],
  [1780444800000, 177278.1942476528],
  [1780531200000, 174188.06124644034],
  [1780617600000, 169751.31880594316],
  [1780704000000, 150741.88866997146],
  [1780790400000, 149611.42300141888],
  [1780876800000, 160185.76384211492],
  [1780963200000, 161722.59690457533],
  [1781049600000, 156184.86670467115],
  [1781136000000, 155068.27984589504],
  [1781222400000, 160100.68792026592],
  [1781308800000, 158658.9481460024],
  [1781395200000, 159946.80906332782],
  [1781481600000, 164030.70167839332],
  [1781568000000, 169971.69779166393],
  [1781654400000, 169365.19899710317],
  [1781740800000, 165808.44388389165],
  [1781827200000, 161283.72437845758],
  [1781913600000, 160948.6311627905],
  [1782000000000, 164392.28102555673],
  [1782086400000, 160796.00211406886],
  [1782172800000, 163522.18645550762],
  [1782259200000, 158481.66482837335],
  [1782345600000, 152783.84434596373],
  [1782432000000, 147722.16279170502],
  [1782518400000, 148649.98948407162],
  [1782604800000, 148304.2554007139],
  [1782691200000, 148314.85992054822],
  [1782777600000, 152581.7966032654],
  [1782864000000, 148619.5543938671],
  [1782950400000, 153472.6024020058],
  [1783036800000, 162243.7989520208],
  [1783123200000, 167691.449709461],
  [1783209600000, 169384.74729599297],
  [1783296000000, 169811.51972316165],
  [1783312363000, 169227.4652463221]],
 'market_caps': [[1751846400000, 26533485698216.99],
  [1751932800000, 26370086338998.305],
  [1752019200000, 27061213234333.78],
  [1752105600000, 28716730871244.258],
  [1752192000000, 30465670349809.316],
  [1752278400000, 30654337408657.83],
  [1752364800000, 30488887456205.07],
  [1752451200000, 30819385404917.04],
  [1752537600000, 31258740549392.49],
  [1752624000000, 32525540543934.215],
  [1752710400000, 34921000730302.3],
  [1752796800000, 36169518489813.67],
  [1752883200000, 36856118013008.92],
  [1752969600000, 37376067302248.95],
  [1753056000000, 39096577669726.35],
  [1753142400000, 39215960978366.26],
  [1753228800000, 39057793349594.484],
  [1753315200000, 37852379251737.85],
  [1753401600000, 38688029004178.16],
  [1753488000000, 38874177075130.98],
  [1753574400000, 39077196730448.59],
  [1753660800000, 40318677556180.195],
  [1753747200000, 39716565448057.98],
  [1753833600000, 39806613299714.71],
  [1753920000000, 40280171870311.266],
  [1754006400000, 39043500652196.35],
  [1754092800000, 36638665425892.56],
  [1754179200000, 35758874484246.82],
  [1754265600000, 36837160842306.984],
  [1754352000000, 39421772450523.08],
  [1754438400000, 38280178186972.52],
  [1754524800000, 39031410608883.41],
  [1754611200000, 41253983001617.69],
  [1754697600000, 42502679661655.32],
  [1754784000000, 45126662598702.41],
  [1754870400000, 44888072846811.18],
  [1754956800000, 44728815449764.27],
  [1755043200000, 48748509301443.484],
  [1755129600000, 50291857626177.17],
  [1755216000000, 48363461535566.805],
  [1755302400000, 46783030292744.34],
  [1755388800000, 46745547691380.73],
  [1755475200000, 47425347484227.8],
  [1755561600000, 45462822241147.9],
  [1755648000000, 42828826170238.664],
  [1755734400000, 45511066543371.18],
  [1755820800000, 44515504993584.29],
  [1755907200000, 50897554940444.375],
  [1755993600000, 50323385247536.766],
  [1756080000000, 50409451691599.87],
  [1756166400000, 46389696093260.73],
  [1756252800000, 48645024286349.33],
  [1756339200000, 47653653087832.89],
  [1756425600000, 47584176350192.93],
  [1756512000000, 46449334474202.4],
  [1756598400000, 46515531348974.8],
  [1756684800000, 46709594686197.43],
  [1756771200000, 45719868956301.82],
  [1756857600000, 45887019368272.09],
  [1756944000000, 47343754745795.86],
  [1757030400000, 45800417563355.984],
  [1757116800000, 45842598701272.9],
  [1757203200000, 45491198729162.63],
  [1757289600000, 45827312481438.35],
  [1757376000000, 45742326179617.12],
  [1757462400000, 45914639643703.89],
  [1757548800000, 46210953587986.92],
  [1757635200000, 47511119281816.375],
  [1757721600000, 50117445713732.08],
  [1757808000000, 49735349796194.32],
  [1757894400000, 49113568724867.9],
  [1757980800000, 48109122402753.62],
  [1758067200000, 47757323794021.31],
  [1758153600000, 48755464992066.37],
  [1758240000000, 48885285782383.21],
  [1758326400000, 47506941069389.92],
  [1758412800000, 47656622935200.734],
  [1758499200000, 47345249620747.95],
  [1758585600000, 44783577702683.695],
  [1758672000000, 44689194992837.42],
  [1758758400000, 44454557342373.06],
  [1758844800000, 41441813632260.42],
  [1758931200000, 43173575424973.414],
  [1759017600000, 43026982094493.555],
  [1759104000000, 44305601982592.375],
  [1759190400000, 45142641454484.6],
  [1759276800000, 44439917110595.086],
  [1759363200000, 46497357467907.96],
  [1759449600000, 47958180213704.71],
  [1759536000000, 48367448917701.836],
  [1759622400000, 48060198166847.74],
  [1759708800000, 48367428592899.414],
  [1759795200000, 50248472663746.086],
  [1759881600000, 47701315347287.664],
  [1759968000000, 48508528010854.43],
  [1760054400000, 46851148227582.87],
  [1760140800000, 41145095571461.29],
  [1760227200000, 40208167969123.914],
  [1760313600000, 44483092980875.79],
  [1760400000000, 45424837048650.65],
  [1760486400000, 44284944135124.56],
  [1760572800000, 42193033655483.53],
  [1760659200000, 41319047816846.734],
  [1760745600000, 40731870083593.44],
  [1760832000000, 41302027682042.6],
  [1760918400000, 42305865010377.99],
  [1761004800000, 42217283741971.586],
  [1761091200000, 41177612693395.516],
  [1761177600000, 40260289629980.52],
  [1761264000000, 40849089149260.59],
  [1761350400000, 41693391798114.15],
  [1761436800000, 41918213550389.67],
  [1761523200000, 44174593987181.81],
  [1761609600000, 43866027108288.7],
  [1761696000000, 42450820802250.81],
  [1761782400000, 41553889658047.31],
  [1761868800000, 40665125028966.984],
  [1761955200000, 41259698780848.99],
  [1762041600000, 41489238284709.92],
  [1762128000000, 41867969530140.04],
  [1762214400000, 38519298365737.98],
  [1762300800000, 35270088580460.02],
  [1762387200000, 36655419214785.2],
  [1762473600000, 35381279099284.38],
  [1762560000000, 36768760915245.64],
  [1762646400000, 36405921913245.25],
  [1762732800000, 38238671283191.92],
  [1762819200000, 38168286897298.05],
  [1762905600000, 36445590585831.65],
  [1762992000000, 36473810140506.65],
  [1763078400000, 34847534260777.47],
  [1763164800000, 33426931691615.645],
  [1763251200000, 33920232704800.496],
  [1763337600000, 33207669152484.27],
  [1763424000000, 32315350660908.98],
  [1763510400000, 33292512119486.09],
  [1763596800000, 32172442318180.83],
  [1763683200000, 30408279617225.273],
  [1763769600000, 29918831533509.055],
  [1763856000000, 29976720848022.58],
  [1763942400000, 30300031045078.547],
  [1764028800000, 31832543463359.355],
  [1764115200000, 31797257348799.113],
  [1764201600000, 32559482238468.6],
  [1764288000000, 32532406733142.082],
  [1764374400000, 32708982884883.863],
  [1764460800000, 32257093226737.26],
  [1764547200000, 32321223299505.79],
  [1764633600000, 30295474303122.81],
  [1764720000000, 32579635787305.74],
  [1764806400000, 34784772794175.01],
  [1764892800000, 33992621701906.113],
  [1764979200000, 32837162962591.645],
  [1765065600000, 32995529300218.33],

In [12]:
import requests
import pandas as pd

coin_id = "ethereum"

url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"

response = requests.get(url)
data = response.json()


prices = data['prices']

df = pd.DataFrame(prices, columns=['timestamp', 'price_usd'])


df['date'] = pd.to_datetime(df['timestamp'], unit='ms').dt.date


df['coin_id'] = coin_id


df = df[['coin_id', 'date', 'price_usd']]

print(df.head())

    coin_id        date    price_usd
0  ethereum  2025-07-07  2571.358192
1  ethereum  2025-07-08  2543.631703
2  ethereum  2025-07-09  2615.775989
3  ethereum  2025-07-10  2772.579563
4  ethereum  2025-07-11  2948.446203

In [13]:
import requests
import pandas as pd
coin_id = "tether"
url=f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"
response = requests.get(url)
response.json()

{'prices': [[1751846400000, 85.50080347794888],
  [1751932800000, 85.8931511462235],
  [1752019200000, 85.71745265403365],
  [1752105600000, 85.72963895170048],
  [1752192000000, 85.7367951539024],
  [1752278400000, 85.85227877587944],
  [1752364800000, 85.85061649402768],
  [1752451200000, 85.84713404704165],
  [1752537600000, 85.9788836587437],
  [1752624000000, 85.99614027111835],
  [1752710400000, 85.92092361254213],
  [1752796800000, 86.09793480404404],
  [1752883200000, 86.18837553232646],
  [1752969600000, 86.18240819304249],
  [1753056000000, 86.18316667030595],
  [1753142400000, 86.30931582921966],
  [1753228800000, 86.374857116835],
  [1753315200000, 86.43062185519801],
  [1753401600000, 86.46549430247569],
  [1753488000000, 86.5079067153148],
  [1753574400000, 86.52243726818574],
  [1753660800000, 86.52789458004021],
  [1753747200000, 86.77257651023056],
  [1753833600000, 87.0447381138731],
  [1753920000000, 87.66199308684169],
  [1754006400000, 87.47687374098898],
  [1754092800000, 87.12827066746021],
  [1754179200000, 87.14631032765092],
  [1754265600000, 87.24786620155615],
  [1754352000000, 87.88635216255223],
  [1754438400000, 87.71607532269402],
  [1754524800000, 87.77852723054042],
  [1754611200000, 87.4444950197738],
  [1754697600000, 87.7304688799895],
  [1754784000000, 87.73905734147515],
  [1754870400000, 87.49382998052141],
  [1754956800000, 87.66325855501688],
  [1755043200000, 87.57426395817158],
  [1755129600000, 87.47159503365995],
  [1755216000000, 87.7507816372641],
  [1755302400000, 87.57103102116423],
  [1755388800000, 87.56566303963238],
  [1755475200000, 87.56915502746656],
  [1755561600000, 87.3340088432775],
  [1755648000000, 87.06237707950677],
  [1755734400000, 87.02531092350665],
  [1755820800000, 87.27411100595894],
  [1755907200000, 87.30311165905988],
  [1755993600000, 87.29882406170462],
  [1756080000000, 87.3250208029963],
  [1756166400000, 87.62524577288721],
  [1756252800000, 87.6555295525574],
  [1756339200000, 87.668600994889],
  [1756425600000, 87.60195342039783],
  [1756512000000, 88.18667861075136],
  [1756598400000, 88.19307898655691],
  [1756684800000, 88.18864003171554],
  [1756771200000, 88.00873910734951],
  [1756857600000, 88.00002982554487],
  [1756944000000, 88.10692319228819],
  [1757030400000, 88.20504329957987],
  [1757116800000, 88.20372141914076],
  [1757203200000, 88.21983030547217],
  [1757289600000, 88.18847972275259],
  [1757376000000, 87.98584666444708],
  [1757462400000, 88.22328147418891],
  [1757548800000, 88.0799119922726],
  [1757635200000, 88.30068969250112],
  [1757721600000, 88.33560397637382],
  [1757808000000, 88.32785330203377],
  [1757894400000, 88.3351205913677],
  [1757980800000, 88.15077362664188],
  [1758067200000, 87.91150541711174],
  [1758153600000, 87.93977895055079],
  [1758240000000, 88.23765391962607],
  [1758326400000, 88.13802082148666],
  [1758412800000, 88.139164151048],
  [1758499200000, 88.1346583356557],
  [1758585600000, 88.37661271837068],
  [1758672000000, 88.82656484403672],
  [1758758400000, 88.80868751998199],
  [1758844800000, 88.81435164667624],
  [1758931200000, 88.72140292397307],
  [1759017600000, 88.71734688895152],
  [1759104000000, 88.70541085832512],
  [1759190400000, 88.7491896902959],
  [1759276800000, 88.8426089698473],
  [1759363200000, 88.72426143807172],
  [1759449600000, 88.76512104961576],
  [1759536000000, 88.78362210279245],
  [1759622400000, 88.76623479806274],
  [1759708800000, 88.75366387498042],
  [1759795200000, 88.75288542329216],
  [1759881600000, 88.77735469974357],
  [1759968000000, 88.78940863615091],
  [1760054400000, 88.91298299022279],
  [1760140800000, 88.90605760034835],
  [1760227200000, 88.89251175516847],
  [1760313600000, 88.86461911659299],
  [1760400000000, 88.75798894617424],
  [1760486400000, 88.84161342512054],
  [1760572800000, 87.87595476797446],
  [1760659200000, 88.03026630514042],
  [1760745600000, 88.09120710681987],
  [1760832000000, 88.07983302001],
  [1760918400000, 88.05341963633443],
  [1761004800000, 87.9260315917352],
  [1761091200000, 88.06928167631557],
  [1761177600000, 87.77158858695039],
  [1761264000000, 87.81763959771669],
  [1761350400000, 87.8550746128549],
  [1761436800000, 87.85314930031927],
  [1761523200000, 87.85195702568677],
  [1761609600000, 88.23580845345],
  [1761696000000, 88.25448192741274],
  [1761782400000, 88.37203661224855],
  [1761868800000, 88.64761241704615],
  [1761955200000, 88.82065097034915],
  [1762041600000, 88.75800024218165],
  [1762128000000, 88.79262580633974],
  [1762214400000, 88.71741213008899],
  [1762300800000, 88.73379965537089],
  [1762387200000, 88.5625678020861],
  [1762473600000, 88.63797690855044],
  [1762560000000, 88.6391072849014],
  [1762646400000, 88.64810924782387],
  [1762732800000, 88.63797258022694],
  [1762819200000, 88.6721395259377],
  [1762905600000, 88.40908429110375],
  [1762992000000, 88.57768259711408],
  [1763078400000, 88.75966779895626],
  [1763164800000, 88.65745562119984],
  [1763251200000, 88.65619087029994],
  [1763337600000, 88.62689987537672],
  [1763424000000, 88.54166896625892],
  [1763510400000, 88.51590926900492],
  [1763596800000, 88.4108653142146],
  [1763683200000, 88.59563784626259],
  [1763769600000, 89.58183385437731],
  [1763856000000, 89.60575823562925],
  [1763942400000, 89.61286862659206],
  [1764028800000, 89.13868923900014],
  [1764115200000, 89.1257096830021],
  [1764201600000, 89.15845599673318],
  [1764288000000, 89.36495482281371],
  [1764374400000, 89.36856427843449],
  [1764460800000, 89.37830938750452],
  [1764547200000, 89.37112064045994],
  [1764633600000, 89.61795485812628],
  [1764720000000, 89.94838626297397],
  [1764806400000, 90.19657892405961],
  [1764892800000, 89.85301183611787],
  [1764979200000, 89.97342634793257],
  [1765065600000, 89.98474906827668],
  [1765152000000, 89.97259854785385],
  [1765238400000, 90.14013168471735],
  [1765324800000, 89.92478216651145],
  [1765411200000, 89.81184332576044],
  [1765497600000, 90.2697965268675],
  [1765584000000, 90.54461267113906],
  [1765670400000, 90.59905295741481],
  [1765756800000, 90.60135439015166],
  [1765843200000, 90.78498450129678],
  [1765929600000, 90.93947274605033],
  [1766016000000, 90.39586093549374],
  [1766102400000, 90.22639439481647],
  [1766188800000, 89.53005618629385],
  [1766275200000, 89.55329537913303],
  [1766361600000, 89.55235938559296],
  [1766448000000, 89.56321616946981],
  [1766534400000, 89.42824078050577],
  [1766620800000, 89.78689321529701],
  [1766707200000, 90.06553404658248],
  [1766793600000, 89.72933722342869],
  [1766880000000, 89.76687299943417],
  [1766966400000, 89.75957578168293],
  [1767052800000, 89.80272658845097],
  [1767139200000, 89.68155241771825],
  [1767225600000, 89.86010638630553],
  [1767312000000, 89.86570510038233],
  [1767398400000, 89.97829419376352],
  [1767484800000, 89.98313618928253],
  [1767571200000, 89.9794305246393],
  [1767657600000, 90.22984949955419],
  [1767744000000, 90.11703926114808],
  [1767830400000, 89.7856606556656],
  [1767916800000, 89.82985588533627],
  [1768003200000, 90.15349935308005],
  [1768089600000, 90.15550929326064],
  [1768176000000, 90.12924081121562],
  [1768262400000, 90.03425860537745],
  [1768348800000, 90.24459865393862],
  [1768435200000, 90.24498201655751],
  [1768521600000, 90.33675913039339],
  [1768608000000, 90.69074291688807],
  [1768694400000, 90.83776783825128],
  [1768780800000, 90.68339984388055],
  [1768867200000, 90.84651949988248],
  [1768953600000, 91.01366646915989],
  [1769040000000, 91.45755919235742],
  [1769126400000, 91.47153938859708],
  [1769212800000, 91.49463866061221],
  [1769299200000, 91.46082307004623],
  [1769385600000, 91.5501111949003],
  [1769472000000, 91.61728715188963],
  [1769558400000, 91.4157096633518],
  [1769644800000, 91.90782656395334],
  [1769731200000, 91.643309265233],
  [1769817600000, 91.54713924898934],
  [1769904000000, 91.58626145922887],
  [1769990400000, 91.60327421251533],
  [1770076800000, 90.37535097601004],
  [1770163200000, 90.30711451597838],
  [1770249600000, 90.25754714478542],
  [1770336000000, 90.15474465431593],
  [1770422400000, 90.54112624507336],
  [1770508800000, 90.54490136224952],
  [1770595200000, 90.5241178608326],
  [1770681600000, 90.73829171749978],
  [1770768000000, 90.54271672929444],
  [1770854400000, 90.68273769379299],
  [1770940800000, 90.50516146580522],
  [1771027200000, 90.51813798097378],
  [1771113600000, 90.52534256474571],
  [1771200000000, 90.5230794828881],
  [1771286400000, 90.74965034353232],
  [1771372800000, 90.59527820056785],
  [1771459200000, 90.76251613145746],
  [1771545600000, 91.01080876764598],
  [1771632000000, 90.69153509343441],
  [1771718400000, 90.70613610314805],
  [1771804800000, 90.69542998936724],
  [1771891200000, 90.9952842406707],
  [1771977600000, 90.92355865051395],
  [1772064000000, 90.96825217790293],
  [1772150400000, 90.99723052968035],
  [1772236800000, 91.0843108367302],
  [1772323200000, 91.10881263967744],
  [1772409600000, 91.07060745984339],
  [1772496000000, 91.56692866442098],
  [1772582400000, 92.01194290116615],
  [1772668800000, 92.1350403232686],
  [1772755200000, 91.79147793686462],
  [1772841600000, 91.93674106068768],
  [1772928000000, 91.93855555140772],
  [1773014400000, 91.93866647186371],
  [1773100800000, 92.31427010585811],
  [1773187200000, 91.97611168078465],
  [1773273600000, 92.23382365807878],
  [1773360000000, 92.3857474199756],
  [1773446400000, 92.61318480892491],
  [1773532800000, 92.59795890805074],
  [1773619200000, 92.57168270053387],
  [1773705600000, 92.26887526783783],
  [1773792000000, 92.40370046156275],
  [1773878400000, 93.17602439378001],
  [1773964800000, 93.09759985912832],
  [1774051200000, 94.03899612829248],
  [1774137600000, 93.99180533550643],
  [1774224000000, 93.78474344342993],
  [1774310400000, 93.27452909445621],
  [1774396800000, 94.2420726393622],
  [1774483200000, 94.09149542203686],
  [1774569600000, 94.25106677881163],
  [1774656000000, 94.7986508310499],
  [1774742400000, 94.71333681092737],
  [1774828800000, 94.7100266864342],
  [1774915200000, 94.2778751883983],
  [1775001600000, 93.40082451580024],
  [1775088000000, 92.63089215232151],
  [1775174400000, 92.97098702014438],
  [1775260800000, 92.75351104211302],
  [1775347200000, 92.97368090066105],
  [1775433600000, 92.94543829190941],
  [1775520000000, 92.95899255212063],
  [1775606400000, 92.84465039924295],
  [1775692800000, 92.28397869788728],
  [1775779200000, 92.46750324062224],
  [1775865600000, 93.13154641287021],
  [1775952000000, 93.1319451835515],
  [1776038400000, 94.50504345578655],
  [1776124800000, 94.95544869782815],
  [1776211200000, 93.19883807207925],
  [1776297600000, 93.40184267183395],
  [1776384000000, 93.061966397283],
  [1776470400000, 92.62671788924118],
  [1776556800000, 92.62257444132158],
  [1776643200000, 92.6279903063258],
  [1776729600000, 93.14745223500783],
  [1776816000000, 93.64193504585802],
  [1776902400000, 93.81946014248018],
  [1776988800000, 94.13360949504937],
  [1777075200000, 94.08390296020438],
  [1777161600000, 94.0859908590388],
  [1777248000000, 94.26435866594068],
  [1777334400000, 94.25157959560823],
  [1777420800000, 94.62726867634119],
  [1777507200000, 94.87785200390216],
  [1777593600000, 94.70846449848001],
  [1777680000000, 94.8711331475398],
  [1777766400000, 94.89945347005639],
  [1777852800000, 94.8917851695458],
  [1777939200000, 95.24118198945749],
  [1778025600000, 95.10541757636773],
  [1778112000000, 94.53397915743437],
  [1778198400000, 94.25207266570669],
  [1778284800000, 94.41764891930137],
  [1778371200000, 94.40690689838186],
  [1778457600000, 94.41155894615403],
  [1778544000000, 95.36341645803249],
  [1778630400000, 95.61376526167236],
  [1778716800000, 95.65307570370081],
  [1778803200000, 95.6840193377221],
  [1778889600000, 95.94918815591298],
  [1778976000000, 95.9819522271874],
  [1779062400000, 95.91245692647317],
  [1779148800000, 96.20091003304816],
  [1779235200000, 96.47444911629424],
  [1779321600000, 96.43055964923398],
  [1779408000000, 96.08260169254757],
  [1779494400000, 95.60498665674767],
  [1779580800000, 95.57829829385082],
  [1779667200000, 95.60328299841848],
  [1779753600000, 95.16414632872262],
  [1779840000000, 95.92847992940565],
  [1779926400000, 95.99958053688873],
  [1780012800000, 95.70729698145198],
  [1780099200000, 94.90014489861531],
  [1780185600000, 94.92941553347354],
  [1780272000000, 94.87407632593278],
  [1780358400000, 95.4192667914143],
  [1780444800000, 95.37820812383718],
  [1780531200000, 96.03213998322617],
  [1780617600000, 95.84478924786677],
  [1780704000000, 95.33292694588775],
  [1780790400000, 95.3253145740299],
  [1780876800000, 94.90710223336191],
  [1780963200000, 95.64643188528824],
  [1781049600000, 95.30197047587932],
  [1781136000000, 95.55894233682353],
  [1781222400000, 95.66497331331372],
  [1781308800000, 95.23153805586901],
  [1781395200000, 95.23709578687804],
  [1781481600000, 95.05170884982935],
  [1781568000000, 94.6840860344782],
  [1781654400000, 94.48677754795501],
  [1781740800000, 94.77816131015243],
  [1781827200000, 94.15958087075545],
  [1781913600000, 94.24667916553423],
  [1782000000000, 94.41629123045772],
  [1782086400000, 94.2232181285519],
  [1782172800000, 94.59515461375916],
  [1782259200000, 95.06601472816668],
  [1782345600000, 94.29433773849134],
  [1782432000000, 94.26603593917363],
  [1782518400000, 94.19834472487662],
  [1782604800000, 94.22278375049866],
  [1782691200000, 94.21903309130714],
  [1782777600000, 94.65533312028089],
  [1782864000000, 94.52490803244486],
  [1782950400000, 95.31761664862599],
  [1783036800000, 95.41402329838093],
  [1783123200000, 95.40700393371937],
  [1783209600000, 95.13301109532756],
  [1783296000000, 95.12512175974344],
  [1783312380000, 95.19600933253086]],
 'market_caps': [[1751846400000, 13562696484370.59],
  [1751932800000, 13621067459348.219],
  [1752019200000, 13599847763176.477],
  [1752105600000, 13602526059698.355],
  [1752192000000, 13613841514901.293],
  [1752278400000, 13657947073480.865],
  [1752364800000, 13684357811465.473],
  [1752451200000, 13691363831663.012],
  [1752537600000, 13716282329900.88],
  [1752624000000, 13749377444704.836],
  [1752710400000, 13745663547888.08],
  [1752796800000, 13798048930554.51],
  [1752883200000, 13860755623350.973],
  [1752969600000, 13922937090184.957],
  [1753056000000, 13926644906051.828],
  [1753142400000, 13952912338264.85],
  [1753228800000, 13987475645306.613],
  [1753315200000, 13996721682463.514],
  [1753401600000, 14051953741069.055],
  [1753488000000, 14104929240143.604],
  [1753574400000, 14128967945922.734],
  [1753660800000, 14153438240168.877],
  [1753747200000, 14196069479466.066],
  [1753833600000, 14245567575009.355],
  [1753920000000, 14355469476206.814],
  [1754006400000, 14324411257874.506],
  [1754092800000, 14280395127661.297],
  [1754179200000, 14283328985379.736],
  [1754265600000, 14299399006239.135],
  [1754352000000, 14405135289893.635],
  [1754438400000, 14376230477600.873],
  [1754524800000, 14379904757274.477],
  [1754611200000, 14344402879650.912],
  [1754697600000, 14417883465849.7],
  [1754784000000, 14431600662646.559],
  [1754870400000, 14393143321240.834],
  [1754956800000, 14423606522130.787],
  [1755043200000, 14417077953627.607],
  [1755129600000, 14435172306396.404],
  [1755216000000, 14481165031013.682],
  [1755302400000, 14524250808263.994],
  [1755388800000, 14570442044603.734],
  [1755475200000, 14593896165378.24],
  [1755561600000, 14561342226926.332],
  [1755648000000, 14543397897925.918],
  [1755734400000, 14534062054329.08],
  [1755820800000, 14580000466008.236],
  [1755907200000, 14585536664126.623],
  [1755993600000, 14592105750424.088],
  [1756080000000, 14596320188598.781],
  [1756166400000, 14647292157816.783],
  [1756252800000, 14655656207756.867],
  [1756339200000, 14659399455792.184],
  [1756425600000, 14658539870925.805],
  [1756512000000, 14758639675085.758],
  [1756598400000, 14780076874357.975],
  [1756684800000, 14816317454531.28],
  [1756771200000, 14788021566385.63],
  [1756857600000, 14786475663292.816],
  [1756944000000, 14814702722767.613],
  [1757030400000, 14846532177390.61],
  [1757116800000, 14865903056851.043],
  [1757203200000, 14897817658933.105],
  [1757289600000, 14892369386411.582],
  [1757376000000, 14858919234837.533],
  [1757462400000, 14903341685706.17],
  [1757548800000, 14893733357575.18],
  [1757635200000, 14956387343248.822],
  [1757721600000, 14976085783834.186],
  [1757808000000, 15015256553035.248],
  [1757894400000, 15036890066170.176],
  [1757980800000, 15007768503194.594],
  [1758067200000, 15015844889125.355],
  [1758153600000, 15033374482741.398],
  [1758240000000, 15099423564373.346],
  [1758326400000, 15110750076607.613],
  [1758412800000, 15110013560805.195],
  [1758499200000, 15153613562076.182],
  [1758585600000, 15202298701698.936],
  [1758672000000, 15344812144400.545],
  [1758758400000, 15367725241094.812],
  [1758844800000, 15404333204813.715],
  [1758931200000, 15387797781327.992],
  [1759017600000, 15453861385810.74],
  [1759104000000, 15467541774266.33],
  [1759190400000, 15475398563184.205],
  [1759276800000, 15519633218132.54],
  [1759363200000, 15519505870498.094],
  [1759449600000, 15598528623861.207],
  [1759536000000, 15647198219013.73],
  [1759622400000, 15644443544647.018],
  [1759708800000, 15712148621063.686],
  [1759795200000, 15711408908768.912],
  [1759881600000, 15751382703835.623],
  [1759968000000, 15796615597857.535],
  [1760054400000, 15856243700335.732],
  [1760140800000, 15886377713124.682],
  [1760227200000, 15926129519008.037],
  [1760313600000, 15977461214408.988],
  [1760400000000, 15956932450774.314],
  [1760486400000, 16045197721624.531],
  [1760572800000, 15871383958713.596],
  [1760659200000, 15962418558527.213],
  [1760745600000, 15993433524456.99],
  [1760832000000, 16018409722632.232],
  [1760918400000, 16015013665376.71],
  [1761004800000, 15991258605334.404],
  [1761091200000, 16024998542109.795],
  [1761177600000, 16010833640733.43],
  [1761264000000, 16027070149016.02],
  [1761350400000, 16067920049605.363],
  [1761436800000, 16067189817756.715],
  [1761523200000, 16090934397421.121],
  [1761609600000, 16162287633409.92],
  [1761696000000, 16170710183951.547],
  [1761782400000, 16201956898711.645],
  [1761868800000, 16252655870374.742],
  [1761955200000, 16289648957049.516],
  [1762041600000, 16283196646510.41],
  [1762128000000, 16288797756733.242],
  [1762214400000, 16275239020958.684],
  [1762300800000, 16275326611275.031],
  [1762387200000, 16247859391846.504],
  [1762473600000, 16260326785103.854],
  [1762560000000, 16260363365007.438],
  [1762646400000, 16262825852638.848],
  [1762732800000, 16262628392704.547],
  [1762819200000, 16274713143407.523],
  [1762905600000, 16227358727747.959],
  [1762992000000, 16301786367161.84],
  [1763078400000, 16333767209483.06],
  [1763164800000, 16310165393932.283],
  [1763251200000, 16315644181900.406],
  [1763337600000, 16311902264137.445],
  [1763424000000, 16296104036392.645],
  [1763510400000, 16273468762941.814],
  [1763596800000, 16255132744004.182],
  [1763683200000, 16371895347447.662],
  [1763769600000, 16553285076332.996],
  [1763856000000, 16540080507157.912],
  [1763942400000, 16532438155159.467],
  [1764028800000, 16435706797048.24],
  [1764115200000, 16446831498456.176],
  [1764201600000, 16455741714406.166],
  [1764288000000, 16493586667791.45],
  [1764374400000, 16498971054813.771],
  [1764460800000, 16500583396056.89],
  [1764547200000, 16498733080741.412],
  [1764633600000, 16543149795768.953],
  [1764720000000, 16603420669823.371],
  [1764806400000, 16713782814565.035],
  [1764892800000, 16669346457760.691],
  [1764979200000, 16691741559479.12],
  [1765065600000, 16704058043872.729],
  [1765152000000, 16703136417840.887],
  [1765238400000, 16734636817003.334],
  [1765324800000, 16701051496718.213],

In [14]:
import requests
import pandas as pd

coin_id = "tether"

url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"

response = requests.get(url)
data = response.json()

if 'prices' in data:
    prices = data['prices']

    df = pd.DataFrame(prices, columns=['timestamp', 'price_usd'])


    df['date'] = pd.to_datetime(df['timestamp'], unit='ms').dt.date


    df['coin_id'] = coin_id


    df = df[['coin_id', 'date', 'price_usd']]

    print(df.head())
else:
    print(f"Error: Could not retrieve price data. API response: {data.get('status', 'No status info.')}")

  coin_id        date  price_usd
0  tether  2025-07-07   1.000050
1  tether  2025-07-08   1.000009
2  tether  2025-07-09   1.000114
3  tether  2025-07-10   1.000244
4  tether  2025-07-11   1.000020

In [15]:
import requests
import pandas as pd

all_coins_price_data = []



market_data_df = pd.DataFrame(all_data)


top_three_coin_ids= ["bitcoin","ethereum","tether"]

for coin_id in top_three_coin_ids:
    url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"
    response = requests.get(url)
    data = response.json()


    if 'prices' in data:
        prices = data['prices']
        df_coin = pd.DataFrame(prices, columns=['timestamp', 'price_usd'])

        df_coin['date'] = pd.to_datetime(df_coin['timestamp'], unit='ms').dt.date
        df_coin['coin_id'] = coin_id

        all_coins_price_data.append(df_coin[['coin_id', 'date', 'price_usd']])
    else:
        print(f"Warning: Could not fetch prices for {coin_id}. API response: {data}")


if all_coins_price_data:
    combined_top_coins_df = pd.concat(all_coins_price_data)
    display(combined_top_coins_df.head())
else:
    print("No historical price data was collected for any of the top coins.")
    combined_top_coins_df = pd.DataFrame(columns=['coin_id', 'date', 'price_usd'])

Warning: Could not fetch prices for tether. API response: {'status': {'error_code': 429, 'error_message': "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}

   coin_id        date      price_usd
0  bitcoin  2025-07-07  109215.197718
1  bitcoin  2025-07-08  108300.716758
2  bitcoin  2025-07-09  108953.191877
3  bitcoin  2025-07-10  111327.530542
4  bitcoin  2025-07-11  115879.650301

In [16]:
combined_top_coins_df

      coin_id        date      price_usd
0     bitcoin  2025-07-07  109215.197718
1     bitcoin  2025-07-08  108300.716758
2     bitcoin  2025-07-09  108953.191877
3     bitcoin  2025-07-10  111327.530542
4     bitcoin  2025-07-11  115879.650301
..        ...         ...            ...
361  ethereum  2026-07-03    1698.401440
362  ethereum  2026-07-04    1756.075758
363  ethereum  2026-07-05    1778.961700
364  ethereum  2026-07-06    1783.452396
365  ethereum  2026-07-06    1775.863235

[732 rows x 3 columns]

In [17]:
import requests
import pandas as pd

all_coins_price_data = []



market_data_df = pd.DataFrame(all_data)


top_three_coin_ids = market_data_df.sort_values(by='market_cap_rank').head(3)

for coin_id in top_three_coin_ids['id']:
    url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"
    response = requests.get(url)
    data = response.json()


    if 'prices' in data:
        prices = data['prices']
        df_coin = pd.DataFrame(prices, columns=['timestamp', 'price_usd'])

        df_coin['date'] = pd.to_datetime(df_coin['timestamp'], unit='ms').dt.date
        df_coin['coin_id'] = coin_id

        all_coins_price_data.append(df_coin[['coin_id', 'date', 'price_usd']])
    else:
        print(f"Warning: Could not fetch prices for {coin_id}. API response: {data}")


if all_coins_price_data:
    combined_top_coins_df = pd.concat(all_coins_price_data)
    display(combined_top_coins_df.head())
else:
    print("No historical price data was collected for any of the top coins.")
    combined_top_coins_df = pd.DataFrame(columns=['coin_id', 'date', 'price_usd'])

   coin_id        date      price_usd
0  bitcoin  2025-07-07  109215.197718
1  bitcoin  2025-07-08  108300.716758
2  bitcoin  2025-07-09  108953.191877
3  bitcoin  2025-07-10  111327.530542
4  bitcoin  2025-07-11  115879.650301

oil price

In [18]:
import pandas as pd
oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10186  2026-06-23  74.62
10187  2026-06-24  71.42
10188  2026-06-25  72.67
10189  2026-06-26  70.30
10190  2026-06-29  71.87

[10191 rows x 2 columns]

In [19]:
oil_df['Date'] = pd.to_datetime(oil_df['Date'])

filtered_df = oil_df[
    (oil_df['Date'] >= '2020-01-01') &
    (oil_df['Date'] <= '2026-02-28')
]

print(filtered_df.head())
print(filtered_df.tail())

           Date  Price
8569 2020-01-02  61.17
8570 2020-01-03  63.00
8571 2020-01-06  63.27
8572 2020-01-07  62.70
8573 2020-01-08  59.65
            Date  Price
10103 2026-02-23  66.36
10104 2026-02-24  65.62
10105 2026-02-25  65.30
10106 2026-02-26  65.10
10107 2026-02-27  66.96

In [20]:
oil_df.to_csv("oil_prices.csv,index=fales")

Stock **Prices**

In [21]:
import yfinance as yf
import pandas as pd

tickers =["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-27"

stocks_df = yf.download(tickers , start=start_date , end=end_date,group_by="ticker")
stocks_df

/tmp/ipykernel_3936/2852614449.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers , start=start_date , end=end_date,group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0
...                  ...           ...           ...           ...       ...
2026-02-20  25406.550781  25663.550781  25379.750000  25571.250000  296600.0
2026-02-23  25678.400391  25771.449219  25609.349609  25713.000000  313700.0
2026-02-24  25641.800781  25641.800781  25327.599609  25424.650391  439100.0
2026-02-25  25512.599609  25652.599609  25428.199219  25482.500000  414200.0
2026-02-26  25556.300781  25572.949219  25400.949219  25496.550781  405200.0

Ticker             ^IXIC                                            \
Price               Open          High           Low         Close
Date
2020-01-01           NaN           NaN           NaN           NaN
2020-01-02   9039.459961   9093.429688   9010.889648   9092.190430
2020-01-03   8976.429688   9065.759766   8976.429688   9020.769531
2020-01-06   8943.500000   9072.410156   8943.500000   9071.469727
2020-01-07   9076.639648   9091.929688   9042.549805   9068.580078
...                  ...           ...           ...           ...
2026-02-20  22542.279297  22948.869141  22539.050781  22886.070312
2026-02-23  22840.970703  22893.220703  22547.119141  22627.269531
2026-02-24  22641.599609  22895.480469  22528.259766  22863.679688
2026-02-25  23005.009766  23169.679688  23004.689453  23152.080078
2026-02-26  23100.580078  23109.460938  22670.800781  22878.380859

Ticker                          ^GSPC                                         \
Price             Volume         Open         High          Low        Close
Date
2020-01-01           NaN          NaN          NaN          NaN          NaN
2020-01-02  2.862700e+09  3244.669922  3258.139893  3235.530029  3257.850098
2020-01-03  2.586520e+09  3226.360107  3246.149902  3222.340088  3234.850098
2020-01-06  2.810450e+09  3217.550049  3246.840088  3214.639893  3246.280029
2020-01-07  2.381740e+09  3241.860107  3244.909912  3232.429932  3237.179932
...                  ...          ...          ...          ...          ...
2026-02-20  8.063070e+09  6843.259766  6915.859863  6836.330078  6909.509766
2026-02-23  8.263920e+09  6901.250000  6916.959961  6819.819824  6837.750000
2026-02-24  7.932270e+09  6837.370117  6899.169922  6815.430176  6890.069824
2026-02-25  8.427450e+09  6915.149902  6952.509766  6915.149902  6946.129883
2026-02-26  9.033470e+09  6944.740234  6947.250000  6859.729980  6908.859863

Ticker
Price             Volume
Date
2020-01-01           NaN
2020-01-02  3.459930e+09
2020-01-03  3.484700e+09
2020-01-06  3.702460e+09
2020-01-07  3.435910e+09
...                  ...
2026-02-20  5.432480e+09
2026-02-23  5.638350e+09
2026-02-24  5.266090e+09
2026-02-25  5.328060e+09
2026-02-26  5.889550e+09

[1597 rows x 15 columns]

In [22]:
stocks_df["^NSEI"].reset_index()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0
...,...,...,...,...,...,...
1592,2026-02-20,25406.550781,25663.550781,25379.750000,25571.250000,296600.0
1593,2026-02-23,25678.400391,25771.449219,25609.349609,25713.000000,313700.0
1594,2026-02-24,25641.800781,25641.800781,25327.599609,25424.650391,439100.0
1595,2026-02-25,25512.599609,25652.599609,25428.199219,25482.500000,414200.0
1596,2026-02-26,25556.300781,25572.949219,25400.949219,25496.550781,405200.0

In [23]:
stocks_df["^GSPC"].reset_index()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09
...,...,...,...,...,...,...
1592,2026-02-20,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09
1593,2026-02-23,6901.250000,6916.959961,6819.819824,6837.750000,5.638350e+09
1594,2026-02-24,6837.370117,6899.169922,6815.430176,6890.069824,5.266090e+09
1595,2026-02-25,6915.149902,6952.509766,6915.149902,6946.129883,5.328060e+09
1596,2026-02-26,6944.740234,6947.250000,6859.729980,6908.859863,5.889550e+09

In [24]:
stocks_df["^IXIC"].reset_index()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09
2,2020-01-03,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09
3,2020-01-06,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09
4,2020-01-07,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09
...,...,...,...,...,...,...
1592,2026-02-20,22542.279297,22948.869141,22539.050781,22886.070312,8.063070e+09
1593,2026-02-23,22840.970703,22893.220703,22547.119141,22627.269531,8.263920e+09
1594,2026-02-24,22641.599609,22895.480469,22528.259766,22863.679688,7.932270e+09
1595,2026-02-25,23005.009766,23169.679688,23004.689453,23152.080078,8.427450e+09
1596,2026-02-26,23100.580078,23109.460938,22670.800781,22878.380859,9.033470e+09

In [25]:
nsei_df = stocks_df['^NSEI'].reset_index()
nsei_df['Ticker'] = '^NSEI'

gspc_df = stocks_df['^GSPC'].reset_index()
gspc_df['Ticker'] = '^GSPC'

ixic_df = stocks_df['^IXIC'].reset_index()
ixic_df['Ticker'] = '^IXIC'

In [26]:
combined_stocks_df = pd.concat([nsei_df, gspc_df, ixic_df])

display(combined_stocks_df.head())

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,^NSEI

In [27]:
import sqlite3

conn = sqlite3.connect("mydb.db")
cursor = conn.cursor()

In [28]:
if 'roi' in market_data_df.columns:
    market_data_df = market_data_df.drop(columns=['roi'])
market_data_df.to_sql("cryptocurrencies", if_exists="replace", index=False, con=conn)

1250

In [29]:
combined_stocks_df.to_sql("stocks",if_exists="replace",index=False,con=conn)

4791

In [30]:
import pandas as pd
df = pd.read_sql("Select * from stocks",con=conn)
df

,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01 00:00:00,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05,^NSEI
1,2020-01-02 00:00:00,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05,^NSEI
2,2020-01-03 00:00:00,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05,^NSEI
3,2020-01-06 00:00:00,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05,^NSEI
4,2020-01-07 00:00:00,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05,^NSEI
...,...,...,...,...,...,...,...
4786,2026-02-20 00:00:00,22542.279297,22948.869141,22539.050781,22886.070312,8.063070e+09,^IXIC
4787,2026-02-23 00:00:00,22840.970703,22893.220703,22547.119141,22627.269531,8.263920e+09,^IXIC
4788,2026-02-24 00:00:00,22641.599609,22895.480469,22528.259766,22863.679688,7.932270e+09,^IXIC
4789,2026-02-25 00:00:00,23005.009766,23169.679688,23004.689453,23152.080078,8.427450e+09,^IXIC
4790,2026-02-26 00:00:00,23100.580078,23109.460938,22670.800781,22878.380859,9.033470e+09,^IXIC

16.Get all stock prices for a given ticker

In [31]:
queries = {}
queries["16. Get all stock prices for a given ticker"] = """
SELECT Date, Open, High, Low, Close, Volume
FROM stocks
WHERE Ticker = '{{ticker_symbol}}'
ORDER BY Date;"""

17.Find the highest closing price for NASDAQ (^IXIC)

In [32]:
queries["17. Find the highest closing price for NASDAQ (^IXIC)"] = """
SELECT MAX(Close) as highest_closing_price
FROM stocks
WHERE Ticker = '^IXIC';"""

18.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

In [33]:
queries["18. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)"] = """
SELECT Date, High, Low, ROUND(High - Low, 2) AS price_difference
FROM stocks
WHERE Ticker = '^GSPC'
ORDER BY price_difference DESC
LIMIT 5;"""

19.Get monthly average closing price for each ticker

In [34]:
queries["19. Get monthly average closing price for each ticker"] = """
SELECT Ticker, strftime('%Y-%m', Date) as year_month,
       ROUND(AVG(Close), 2) as average_closing_price
FROM stocks
GROUP BY Ticker, year_month
ORDER BY Ticker, year_month;"""

20.Get average trading volume of NSEI in 2024

In [35]:
queries["20. Get average trading volume of NSEI in 2024"] = """
SELECT ROUND(AVG(Volume), 2) AS average_trading_volume
FROM stocks
WHERE Ticker = '^NSEI' AND strftime('%Y', Date) = '2024';"""

In [36]:
oil_df.to_sql("oil",if_exists="replace",index=False,con=conn)

10191

In [37]:
import pandas as pd
df = pd.read_sql("Select * from oil",con=conn)
df

                      Date  Price
0      1986-01-02 00:00:00  25.56
1      1986-01-03 00:00:00  26.00
2      1986-01-06 00:00:00  26.53
3      1986-01-07 00:00:00  25.85
4      1986-01-08 00:00:00  25.87
...                    ...    ...
10186  2026-06-23 00:00:00  74.62
10187  2026-06-24 00:00:00  71.42
10188  2026-06-25 00:00:00  72.67
10189  2026-06-26 00:00:00  70.30
10190  2026-06-29 00:00:00  71.87

[10191 rows x 2 columns]

11.Find the highest oil price in the last 5 years.

In [38]:
queries["11. Highest oil price (5 years)"] = """
SELECT strftime('%Y-%m-%d', Date) as date, MAX(Price) as highest_price
FROM oil_prices
WHERE Date >= date('now', '-5 years')
GROUP BY strftime('%Y-%m-%d', Date)
ORDER BY highest_price DESC
LIMIT 1;"""

12.Get the average oil price per year.

In [39]:
queries["12. Avg oil price per year"] = """
SELECT strftime('%Y', Date) as year,
       ROUND(AVG(Price), 2) as avg_price
FROM oil_prices
GROUP BY year
ORDER BY year DESC;"""

13.Show oil prices during COVID crash (March–April 2020).

In [40]:
queries["13. Oil prices during COVID crash"] = """
SELECT strftime('%Y-%m-%d', Date) as date, Price,
       LAG(Price) OVER (ORDER BY Date) as prev_price,
       ROUND(Price - LAG(Price) OVER (ORDER BY Date), 2) as daily_change
FROM oil_prices
WHERE Date >= '2020-03-01' AND Date <= '2020-04-30'
ORDER BY Date;"""

14.Find the lowest price of oil in the last 10 years.

In [41]:
queries["14. Lowest oil price (10 years)"] = """
SELECT strftime('%Y-%m-%d', Date) as date, MIN(Price) as lowest_price
FROM oil_prices
WHERE Date >= date('now', '-10 years')
GROUP BY strftime('%Y-%m-%d', Date)
ORDER BY lowest_price ASC
LIMIT 1;"""

15.Calculate the volatility of oil prices (max-min difference per year).

In [42]:
queries["15. Oil price volatility per year"] = """
SELECT strftime('%Y', Date) as year,
       MAX(Price) - MIN(Price) as volatility
FROM oil_prices
GROUP BY year
ORDER BY volatility DESC;"""

In [43]:
combined_top_coins_df.to_sql("crypto_prices",if_exists="replace",index=False,con=conn)

1098

In [45]:
import pandas as pd
import sqlite3

with sqlite3.connect("market_data.db") as conn:
    df = pd.read_sql("Select * from all_data", con=conn)
df

DatabaseError: Execution failed on sql 'Select * from all_data': no such table: all_data

In [46]:
import sqlite3
import pandas as pd

In [47]:
conn=sqlite3.connect("mydb.db")
cursor = conn.cursor()

In [57]:
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

print(tables)

               name
0            stocks
1               oil
2     crypto_prices
3  cryptocurrencies

6.Find the highest daily price of Bitcoin in the last 365 days.

In [48]:
queries["6. Highest Bitcoin price (last 365 days)"] = """
SELECT date, MAX(price_usd) as highest_price
FROM crypto_prices
WHERE coin_id = 'bitcoin'
  AND date >= date('now', '-365 days')
GROUP BY date
ORDER BY highest_price DESC
LIMIT 1;"""

7.Calculate the average daily price of Ethereum in the past 1 year.

In [49]:
queries["7. Ethereum average price (1 year)"] = """
SELECT coin_id,
       ROUND(AVG(price_usd), 2) as avg_price,
       MIN(price_usd) as min_price,
       MAX(price_usd) as max_price
FROM crypto_prices
WHERE coin_id = 'ethereum'
  AND date >= date('now', '-1 year')
GROUP BY coin_id;"""

8.Show the daily price trend of Bitcoin in june 2026 .

In [50]:
queries["8. Bitcoin daily price trend (jun 2026)"] = """
SELECT date,
       price_usd,
       LAG(price_usd) OVER (ORDER BY date) as prev_price,
       ROUND(price_usd - LAG(price_usd) OVER (ORDER BY date), 2) as price_change
FROM crypto_prices
WHERE coin_id = 'bitcoin'
  AND date >= '2025-12-01'
  AND date < '2026-06-01'
ORDER BY date;"""

9.Find the coin with the highest average price over 1 year.

In [51]:
queries["9. Coin with highest avg price (1 year)"] = """
SELECT coin_id,
       ROUND(AVG(price_usd), 2) as avg_price
FROM crypto_prices
WHERE date >= date('now', '-1 year')
GROUP BY coin_id
ORDER BY avg_price DESC
LIMIT 1;"""

10.Get the % change in Bitcoin’s price between jan 2026 and jun 2026

In [52]:
queries["10. Bitcoin % change ( jan 2020 vs jun 2026)"] = """
SELECT
    MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END) as jan_2026,
    MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END) as jun_2026,
    ROUND(((MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END) -
            MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END)) * 100.0 /
            NULLIF(MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END), 0)), 2) as pct_change
FROM crypto_prices
WHERE coin_id = 'bitcoin';"""

cryptocurrencies

In [ ]:
market_data_df.to_sql("cryptocurrencies", if_exists="replace", index=False, con=conn)

1250

In [ ]:
import pandas as pd
df = pd.read_sql("Select * from cryptocurrencies",con=conn)
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,circulating_supply,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,6.025146e+06,120815898744084,1,120815898744084,1.921319e+12,6.080190e+06,...,2.005269e+07,2.005269e+07,2.100000e+07,11187013.00,-46.14160,2025-10-06T18:57:42.558Z,3993.420000,1.507769e+05,2013-07-05T00:00:00.000Z,2026-07-06T04:17:11.920Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1.693980e+05,20444101093832,2,20444101093832,9.735510e+11,1.714460e+05,...,1.206832e+08,1.206832e+08,NaN,431946.00,-60.78246,2025-08-24T19:21:03.333Z,28.130000,6.020720e+05,2015-10-20T00:00:00.000Z,2026-07-06T04:17:12.318Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,9.514000e+01,17538446131551,3,18058596575904,3.435629e+12,9.539000e+01,...,1.843345e+11,1.898014e+11,NaN,105.52,-9.81118,2025-01-25T16:51:57.989Z,36.860000,1.581855e+02,2015-03-02T00:00:00.000Z,2026-07-06T04:17:14.073Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5.565000e+04,7500511797301,4,7500511797301,7.633764e+10,5.649600e+04,...,1.347824e+08,1.347824e+08,2.000000e+08,121422.00,-54.16798,2025-10-13T08:41:24.131Z,2.580000,2.152929e+06,2017-10-19T00:00:00.000Z,2026-07-06T04:17:11.707Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,9.522000e+01,6931212082568,5,6940124781802,6.397840e+11,9.544000e+01,...,7.278785e+10,7.288145e+10,NaN,96.98,-1.78532,2026-05-20T14:19:58.071Z,65.310000,4.584493e+01,2021-05-19T13:14:05.611Z,2026-07-06T04:17:01.848Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,fartboy,$fartboy,Fartboy,https://coin-images.coingecko.com/coins/images...,8.192510e-01,818748565,1248,818748565,4.582649e+07,8.532460e-01,...,9.993869e+08,9.993869e+08,9.994405e+08,16.90,-95.16728,2025-02-12T21:45:25.974Z,0.620216,3.166843e+01,2026-02-05T15:31:35.053Z,2026-07-06T04:17:37.671Z
1246,bobo-coin-2,bobo,Bobo,https://coin-images.coingecko.com/coins/images...,8.176760e-01,817822934,1245,817822934,4.851703e+07,8.506960e-01,...,9.999989e+08,9.999989e+08,NaN,2.27,-63.98290,2026-05-10T09:55:26.125Z,0.648082,2.625735e+01,2026-06-05T07:25:15.391Z,2026-07-06T04:17:45.142Z
1247,midas-re7-ethereum,mre7eth,Midas Re7 Ethereum,https://coin-images.coingecko.com/coins/images...,1.704840e+05,815484361,1249,815484361,NaN,1.722100e+05,...,4.783344e+03,4.783344e+03,NaN,228779.00,-25.50992,2026-05-06T11:25:10.570Z,94.900000,1.794689e+05,2026-04-30T19:25:08.336Z,2026-07-06T04:15:43.073Z
1248,sandisk-ondo-tokenized,sndkon,SanDisk (Ondo Tokenized),https://coin-images.coingecko.com/coins/images...,1.742730e+05,815435547,1247,815435547,1.333260e+08,1.810190e+05,...,4.679072e+03,4.679072e+03,NaN,223407.00,-21.76156,2026-06-25T20:10:21.157Z,52284.000000,2.343080e+02,2026-03-30T23:54:37.586Z,2026-07-06T04:17:48.049Z
1249,stader,sd,Stader,https://coin-images.coingecko.com/coins/images...,1.133000e+01,814939545,1250,1360184890,1.720566e+07,1.158000e+01,...,7.189666e+07,1.200000e+08,1.500000e+08,2304.28,-99.50752,2022-03-15T14:33:38.024Z,10.540000,7.623370e+00,2026-07-01T07:46:29.847Z,2026-07-06T04:17:48.819Z

cryptocurrencies  Queries

In [58]:
import sqlite3
import pandas as pd

In [59]:
conn = sqlite3.connect("market_data.db")

1. Top 3 cryptocurrencies by market cap

In [60]:
queries = {
    "1. Top 3 cryptocurrencies by market cap": """
SELECT name, symbol, market_cap, market_cap_rank, current_price
FROM cryptocurrencies
ORDER BY market_cap_rank
LIMIT 3;""",
}

In [61]:
df.nlargest(3, 'market_cap')[['name', 'symbol', 'market_cap']]

       name symbol       market_cap
0   Bitcoin    btc  120815898744084
1  Ethereum    eth   20444101093832
2    Tether   usdt   17538446131551

2.List all coins where circulating supply exceeds 90% of total supply.

In [62]:
queries["2. Coins with >90% circulating supply"] = """
SELECT name, symbol, circulating_supply, total_supply,
       ROUND((circulating_supply*100.0/NULLIF(total_supply, 0)),2) as supply_percentage
FROM cryptocurrencies
WHERE total_supply > 0
  AND (circulating_supply*100.0/total_supply) > 90
ORDER BY supply_percentage DESC;"""

In [63]:
df[df['circulating_supply'] > 0.9 * df['total_supply']][
    ['name', 'symbol', 'circulating_supply', 'total_supply']
]

,name,symbol,circulating_supply,total_supply
0,Bitcoin,btc,2.005269e+07,2.005269e+07
1,Ethereum,eth,1.206832e+08,1.206832e+08
2,Tether,usdt,1.843345e+11,1.898014e+11
3,BNB,bnb,1.347824e+08,1.347824e+08
4,USDC,usdc,7.278785e+10,7.288145e+10
...,...,...,...,...
1243,USP Yield Optimized Stablecoin,usp,7.796015e+06,7.796015e+06
1245,Fartboy,$fartboy,9.993869e+08,9.993869e+08
1246,Bobo,bobo,9.999989e+08,9.999989e+08
1247,Midas Re7 Ethereum,mre7eth,4.783344e+03,4.783344e+03
1248,SanDisk (Ondo Tokenized),sndkon,4.679072e+03,4.679072e+03

3.Get coins that are within 10% of their all-time-high (ATH).

In [64]:
queries["3. Coins within 10% of ATH"] = """
SELECT name, symbol, current_price, ath,
       ROUND((current_price*100.0/ath),2) as percent_of_ath
FROM cryptocurrencies
WHERE ath > 0
  AND (current_price*100.0/ath) >= 90
ORDER BY percent_of_ath DESC;"""

In [65]:
df[df['ath_change_percentage'] >= -10][
    ['name', 'symbol', 'current_price', 'ath', 'ath_change_percentage']
]

,name,symbol,current_price,ath,ath_change_percentage
2,Tether,usdt,95.14,105.52,-9.81118
4,USDC,usdc,95.22,96.98,-1.78532
8,Figure Heloc,figr_heloc,96.31,100.40,-4.07234
9,Hyperliquid,hype,6794.84,7251.06,-6.29167
12,Rain,rain,1.44,1.53,-5.71400
...,...,...,...,...,...
1170,Defi.money,money,95.05,97.24,-2.08902
1172,Midas mRe7YIELD,mre7yield,101.72,103.94,-2.13422
1176,Backed GOVIES 0-6 months EURO,bc3m,13744.16,14232.32,-3.41633
1206,iShares Russell 1000 Growth ETF (Ondo Tokenize...,iwfon,46474.00,51011.00,-8.87745
1215,Taiwan Semiconductor Manufacturing (Ondo Token...,tsmon,42481.00,45602.00,-6.51170

4.Find the average market cap rank of coins with volume above $1B.

In [66]:
queries["4. Avg market cap rank (volume > $1B)"] = """
SELECT ROUND(AVG(market_cap_rank), 2) as avg_rank,
       COUNT(*) as coin_count
FROM cryptocurrencies
WHERE total_volume > 1000000000;"""

In [67]:
df[df['total_volume'] > 1_000_000_000]['market_cap_rank'].mean()

np.float64(291.9673913043478)

5.Get the most recently updated coin.

In [68]:
queries["5. Most recently updated coin"] = """
SELECT name, symbol, current_price, market_cap, last_updated
FROM cryptocurrencies
ORDER BY last_updated DESC
LIMIT 1;"""

In [69]:
df.loc[df['last_updated'].idxmax()][
    ['name', 'symbol', 'last_updated']
]

name                AITECH Cloud Network
symbol                               acn
last_updated    2026-07-06T04:17:49.099Z
Name: 1115, dtype: object

Join Queries (Cross-Market Analysis)

21.Compare Bitcoin vs Oil average price in 2026.

In [70]:
queries["21. Compare Bitcoin vs Oil average price in 2026"] = """
SELECT
  (SELECT ROUND(AVG(cp.price_usd), 2)
   FROM crypto_prices cp
   WHERE cp.coin_id = 'bitcoin' AND strftime('%Y', cp.date) = '2026') AS avg_bitcoin_price_2026,
  (SELECT ROUND(AVG(o.Price), 2)
   FROM oil o
   WHERE strftime('%Y', o.Date) = '2026') AS avg_oil_price_2026;"""

22.Check if Bitcoin moves with S&P 500 (correlation idea).

In [71]:
queries["22. Check if Bitcoin moves with S&P 500 (correlation idea)"] = """
SELECT cp.date, cp.price_usd as bitcoin, s.Close as sp500
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE cp.coin_id = 'bitcoin'
  AND s.Ticker = '^GSPC'
ORDER BY cp.date DESC
LIMIT 30;"""

23.Compare Ethereum and NASDAQ daily prices for 2026.

In [72]:
queries["23. Compare Ethereum and NASDAQ daily prices for 2026"] = """
SELECT cp.date, cp.price_usd as ethereum, s.Close as nasdaq
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE cp.coin_id = 'ethereum'
  AND s.Ticker = '^IXIC'
ORDER BY cp.date DESC
LIMIT 30;"""

24.Find days when oil price spiked and compare with Bitcoin price change.

In [73]:
queries["24. Find days when oil price spiked and compare with Bitcoin price change"] = """
SELECT DATE(op.Date) as date, op.Price as oil, cp.price_usd as bitcoin
FROM oil op
JOIN crypto_prices cp ON DATE(op.Date) = cp.date
WHERE cp.coin_id = 'bitcoin'
ORDER BY op.Date DESC
LIMIT 30;"""

25.Compare top 3 coins daily price trend vs Nifty (^NSEI).

In [74]:
queries["25. Compare top 3 coins daily price trend vs Nifty (^NSEI)"] = """
SELECT
    cp.date,
    s.Close AS nifty_close_price,
    MAX(CASE WHEN cp.coin_id = 'bitcoin' THEN cp.price_usd ELSE NULL END) AS bitcoin_price,
    MAX(CASE WHEN cp.coin_id = 'ethereum' THEN cp.price_usd ELSE NULL END) AS ethereum_price,
    MAX(CASE WHEN cp.coin_id = 'tether' THEN cp.price_usd ELSE NULL END) AS tether_price
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE s.Ticker = '^NSEI'
  AND cp.coin_id IN ('bitcoin', 'ethereum', 'tether')
GROUP BY cp.date, s.Close
ORDER BY cp.date DESC
LIMIT 30;"""

26.Compare stock prices (^GSPC) with crude oil prices on the same dates

In [75]:
queries["26. Compare stock prices (^GSPC) with crude oil prices on the same dates"] = """
SELECT
    s.Date,
    s.Close AS gspc_close_price,
    o.Price AS oil_price
FROM stocks s
JOIN oil o ON s.Date = o.Date
WHERE s.Ticker = '^GSPC'
ORDER BY s.Date DESC
LIMIT 30;"""

27.Correlate Bitcoin closing price with crude oil closing price (same date)

In [76]:
queries["27. Correlate Bitcoin closing price with crude oil closing price (same date)"] = """
SELECT
    cp.date,
    cp.price_usd AS bitcoin_price,
    o.Price AS oil_price
FROM crypto_prices cp
JOIN oil o ON cp.date = DATE(o.Date)
WHERE cp.coin_id = 'bitcoin'
ORDER BY cp.date DESC
LIMIT 30;"""

28.Compare NASDAQ (^IXIC) with Ethereum price trends

In [77]:
queries["28. Compare NASDAQ (^IXIC) with Ethereum price trends"] = """
SELECT
    cp.date,
    cp.price_usd AS ethereum_price,
    s.Close AS nasdaq_close_price
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE cp.coin_id = 'ethereum'
  AND s.Ticker = '^IXIC'
ORDER BY cp.date DESC
LIMIT 30;"""

29.Join top 3 crypto coins with stock indices for 2026.

In [78]:
queries["29. Join top 3 crypto coins with stock indices for 2026."] = """
SELECT
    cp.date,
    MAX(CASE WHEN cp.coin_id = 'bitcoin' THEN cp.price_usd ELSE NULL END) AS bitcoin_price,
    MAX(CASE WHEN cp.coin_id = 'ethereum' THEN cp.price_usd ELSE NULL END) AS ethereum_price,
    MAX(CASE WHEN cp.coin_id = 'tether' THEN cp.price_usd ELSE NULL END) AS tether_price,
    MAX(CASE WHEN s.Ticker = '^GSPC' THEN s.Close ELSE NULL END) AS gspc_close_price,
    MAX(CASE WHEN s.Ticker = '^IXIC' THEN s.Close ELSE NULL END) AS ixic_close_price,
    MAX(CASE WHEN s.Ticker = '^NSEI' THEN s.Close ELSE NULL END) AS nsei_close_price
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE strftime('%Y', cp.date) = '2026'
  AND cp.coin_id IN ('bitcoin', 'ethereum', 'tether')
  AND s.Ticker IN ('^GSPC', '^IXIC', '^NSEI')
GROUP BY cp.date
ORDER BY cp.date DESC
LIMIT 30;"""

30.Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

In [79]:
queries["30. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison"] = """
SELECT
    cp.date,
    cp.price_usd AS bitcoin_price,
    o.Price AS oil_price,
    s.Close AS gspc_close_price
FROM crypto_prices cp
JOIN oil o ON cp.date = DATE(o.Date)
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE cp.coin_id = 'bitcoin'
  AND s.Ticker = '^GSPC'
ORDER BY cp.date DESC
LIMIT 30;"""

In [80]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 62.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 103.5 MB/s eta 0:00:00
--2026-07-06 04:50:29--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.6.1/cloudflared-linux-amd64 [following]
--2026-07-06 04:50:29--  https://github.com/cloudflare/cloudflared/releases/download/2026.6.1/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/74ac6867-a1bf-4352-b955-c16fbb86d0f6?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-07-06T05%3A44%3A49Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-07-06T04%3A43%3A55Z&ske=2026-07-06T05%3A44%3A49Z&sks=b&skv=2018-11-09&sig=ueurHwj8KPDAigZa4olIlGpwkj11e%2FU021jsM5Kb4tw%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MzMxNTE4NywibmJmIjoxNzgzMzEzMzg3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.kCI1T4n-paynCYw1DqW-fVbMtCVWnKWkFh1wmAj5d_A&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-07-06 04:50:29--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/74ac6867-a1bf-4352-b955-c16fbb86d0f6?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-07-06T05%3A44%3A49Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-07-06T04%3A43%3A55Z&ske=2026-07-06T05%3A44%3A49Z&sks=b&skv=2018-11-09&sig=ueurHwj8KPDAigZa4olIlGpwkj11e%2FU021jsM5Kb4tw%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MzMxNTE4NywibmJmIjoxNzgzMzEzMzg3LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.kCI1T4n-paynCYw1DqW-fVbMtCVWnKWkFh1wmAj5d_A&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39244939 (37M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64’

cloudflared-linux-a 100%[===================>]  37.43M   167MB/s    in 0.2s

2026-07-06 04:50:29 (167 MB/s) - ‘cloudflared-linux-amd64’ saved [39244939/39244939]

nohup: appending output to 'nohup.out'

In [81]:
!pip install streamlit-option-menu

Collecting streamlit-option-menu
  Downloading streamlit_option_menu-0.4.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: streamlit>=1.36 in /usr/local/lib/python3.12/dist-packages (from streamlit-option-menu) (1.58.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.9.3)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (4.14.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit>=1.36->streamlit-option-menu) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2026.6.17)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit>=1.36->streamlit-option-menu) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2026.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)
Downloading streamlit_option_menu-0.4.0-py3-none-any.whl (829 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.3/829.3 kB 11.2 MB/s eta 0:00:00
Installing collected packages: streamlit-option-menu
Successfully installed streamlit-option-menu-0.4.0

In [82]:
%%writefile app.py

import streamlit as st
import pandas as pd
import sqlite3
from datetime import datetime

# Define SQL_QUERIES dictionary
SQL_QUERIES = {
    "1. Top 3 cryptocurrencies by market cap": """
SELECT name, symbol, market_cap, market_cap_rank, current_price
FROM cryptocurrencies
ORDER BY market_cap_rank
LIMIT 3;""",
    "2. Coins with >90% circulating supply": """
SELECT name, symbol, circulating_supply, total_supply,
       ROUND((circulating_supply*100.0/NULLIF(total_supply, 0)),2) as supply_percentage
FROM cryptocurrencies
WHERE total_supply > 0
  AND (circulating_supply*100.0/total_supply) > 90
ORDER BY supply_percentage DESC;""",
    "3. Coins within 10% of ATH": """
SELECT name, symbol, current_price, ath,
       ROUND((current_price*100.0/ath),2) as percent_of_ath
FROM cryptocurrencies
WHERE ath > 0
  AND (current_price*100.0/ath) >= 90
ORDER BY percent_of_ath DESC;""",
    "4. Avg market cap rank (volume > $1B)": """
SELECT ROUND(AVG(market_cap_rank), 2) as avg_rank,
       COUNT(*) as coin_count
FROM cryptocurrencies
WHERE total_volume > 1000000000;""",
    "5. Most recently updated coin": """
SELECT name, symbol, current_price, market_cap, last_updated
FROM cryptocurrencies
ORDER BY last_updated DESC
LIMIT 1;""",
    "6. Highest Bitcoin price (last 365 days)": """
SELECT date, MAX(price_usd) as highest_price
FROM crypto_prices
WHERE coin_id = 'bitcoin'
  AND date >= date('now', '-365 days')
GROUP BY date
ORDER BY highest_price DESC
LIMIT 1;""",
    "7. Ethereum average price (1 year)": """
SELECT coin_id,
       ROUND(AVG(price_usd), 2) as avg_price,
       MIN(price_usd) as min_price,
       MAX(price_usd) as max_price
FROM crypto_prices
WHERE coin_id = 'ethereum'
  AND date >= date('now', '-1 year')
GROUP BY coin_id;""",
    "8. Bitcoin daily price trend (jun 2026)": """
SELECT date,
       price_usd,
       LAG(price_usd) OVER (ORDER BY date) as prev_price,
       ROUND(price_usd - LAG(price_usd) OVER (ORDER BY date), 2) as price_change
FROM crypto_prices
WHERE coin_id = 'bitcoin'
  AND date >= '2025-12-01'
  AND date < '2026-06-01'
ORDER BY date;""",
    "9. Coin with highest avg price (1 year)": """
SELECT coin_id,
       ROUND(AVG(price_usd), 2) as avg_price
FROM crypto_prices
WHERE date >= date('now', '-1 year')
GROUP BY coin_id
ORDER BY avg_price DESC
LIMIT 1;""",
    "10. Bitcoin % change ( jan 2020 vs jun 2026)": """
SELECT
    MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END) as jan_2026,
    MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END) as jun_2026,
    ROUND(((MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END) -
            MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END)) * 100.0 /
            NULLIF(MAX(CASE WHEN date >= '2026-01-01' AND date < '2026-06-01' THEN price_usd END), 0)), 2) as pct_change
FROM crypto_prices
WHERE coin_id = 'bitcoin';""",
    "11. Highest oil price (5 years)": """
SELECT strftime('%Y-%m-%d', Date) as date, MAX(Price) as highest_price
FROM oil
WHERE Date >= date('now', '-5 years')
GROUP BY date
ORDER BY highest_price DESC
LIMIT 1;""",
    "12. Avg oil price per year": """
SELECT strftime('%Y', Date) as year,
       ROUND(AVG(Price), 2) as avg_price
FROM oil
GROUP BY year
ORDER BY year DESC;""",
    "13. Oil prices during COVID crash": """
SELECT strftime('%Y-%m-%d', Date) as date, Price,
       LAG(Price) OVER (ORDER BY Date) as prev_price,
       ROUND(Price - LAG(Price) OVER (ORDER BY Date), 2) as daily_change
FROM oil
WHERE Date >= '2020-03-01' AND Date <= '2020-04-30'
ORDER BY Date;""",
    "14. Lowest oil price (10 years)": """
SELECT strftime('%Y-%m-%d', Date) as date, MIN(Price) as lowest_price
FROM oil
WHERE Date >= date('now', '-10 years')
GROUP BY date
ORDER BY lowest_price ASC
LIMIT 1;""",
    "15. Oil price volatility per year": """
SELECT strftime('%Y', Date) as year,
       MAX(Price) - MIN(Price) as volatility
FROM oil
GROUP BY year
ORDER BY volatility DESC;""",
    "16. Get all stock prices for a given ticker": """
SELECT Date, Open, High, Low, Close, Volume
FROM stocks
WHERE Ticker = '{{ticker_symbol}}'
ORDER BY Date;""",
    "17. Find the highest closing price for NASDAQ (^IXIC)": """
SELECT MAX(Close) as highest_closing_price
FROM stocks
WHERE Ticker = '^IXIC';""",
    "18. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)": """
SELECT Date, High, Low, ROUND(High - Low, 2) AS price_difference
FROM stocks
WHERE Ticker = '^GSPC'
ORDER BY price_difference DESC
LIMIT 5;""",
    "19. Get monthly average closing price for each ticker": """
SELECT Ticker, strftime('%Y-%m', Date) as year_month,
       ROUND(AVG(Close), 2) as average_closing_price
FROM stocks
GROUP BY Ticker, year_month
ORDER BY Ticker, year_month;""",
    "20. Get average trading volume of NSEI in 2024": """
SELECT ROUND(AVG(Volume), 2) AS average_trading_volume
FROM stocks
WHERE Ticker = '^NSEI' AND strftime('%Y', Date) = '2024';""",
    "21. Compare Bitcoin vs Oil average price in 2026": """
SELECT
  (SELECT ROUND(AVG(cp.price_usd), 2)
   FROM crypto_prices cp
   WHERE cp.coin_id = 'bitcoin' AND strftime('%Y', cp.date) = '2026') AS avg_bitcoin_price_2026,
  (SELECT ROUND(AVG(o.Price), 2)
   FROM oil o
   WHERE strftime('%Y', o.Date) = '2026') AS avg_oil_price_2026;""",
    "22. Check if Bitcoin moves with S&P 500 (correlation idea)": """
SELECT cp.date, cp.price_usd as bitcoin, s.Close as sp500
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE cp.coin_id = 'bitcoin'
  AND s.Ticker = '^GSPC'
ORDER BY cp.date DESC
LIMIT 30;""",
    "23. Compare Ethereum and NASDAQ daily prices for 2026": """
SELECT cp.date, cp.price_usd as ethereum, s.Close as nasdaq
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE cp.coin_id = 'ethereum'
  AND s.Ticker = '^IXIC'
ORDER BY cp.date DESC
LIMIT 30;""",
    "24. Find days when oil price spiked and compare with Bitcoin price change": """
SELECT DATE(op.Date) as date, op.Price as oil, cp.price_usd as bitcoin
FROM oil op
JOIN crypto_prices cp ON DATE(op.Date) = cp.date
WHERE cp.coin_id = 'bitcoin'
ORDER BY op.Date DESC
LIMIT 30;""",
    "25. Compare top 3 coins daily price trend vs Nifty (^NSEI)": """
SELECT
    cp.date,
    s.Close AS nifty_close_price,
    MAX(CASE WHEN cp.coin_id = 'bitcoin' THEN cp.price_usd ELSE NULL END) AS bitcoin_price,
    MAX(CASE WHEN cp.coin_id = 'ethereum' THEN cp.price_usd ELSE NULL END) AS ethereum_price,
    MAX(CASE WHEN cp.coin_id = 'tether' THEN cp.price_usd ELSE NULL END) AS tether_price
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE s.Ticker = '^NSEI'
  AND cp.coin_id IN ('bitcoin', 'ethereum', 'tether')
GROUP BY cp.date, s.Close
ORDER BY cp.date DESC
LIMIT 30;""",
    "26. Compare stock prices (^GSPC) with crude oil prices on the same dates": """
SELECT
    s.Date,
    s.Close AS gspc_close_price,
    o.Price AS oil_price
FROM stocks s
JOIN oil o ON s.Date = o.Date
WHERE s.Ticker = '^GSPC'
ORDER BY s.Date DESC
LIMIT 30;""",
    "27. Correlate Bitcoin closing price with crude oil closing price (same date)": """
SELECT
    cp.date,
    cp.price_usd AS bitcoin_price,
    o.Price AS oil_price
FROM crypto_prices cp
JOIN oil o ON cp.date = DATE(o.Date)
WHERE cp.coin_id = 'bitcoin'
ORDER BY cp.date DESC
LIMIT 30;""",
    "28. Compare NASDAQ (^IXIC) with Ethereum price trends": """
SELECT
    cp.date,
    cp.price_usd AS ethereum_price,
    s.Close AS nasdaq_close_price
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE cp.coin_id = 'ethereum'
  AND s.Ticker = '^IXIC'
ORDER BY cp.date DESC
LIMIT 30;""",
    "29. Join top 3 crypto coins with stock indices for 2026.": """
SELECT
    cp.date,
    MAX(CASE WHEN cp.coin_id = 'bitcoin' THEN cp.price_usd ELSE NULL END) AS bitcoin_price,
    MAX(CASE WHEN cp.coin_id = 'ethereum' THEN cp.price_usd ELSE NULL END) AS ethereum_price,
    MAX(CASE WHEN cp.coin_id = 'tether' THEN cp.price_usd ELSE NULL END) AS tether_price,
    MAX(CASE WHEN s.Ticker = '^GSPC' THEN s.Close ELSE NULL END) AS gspc_close_price,
    MAX(CASE WHEN s.Ticker = '^IXIC' THEN s.Close ELSE NULL END) AS ixic_close_price,
    MAX(CASE WHEN s.Ticker = '^NSEI' THEN s.Close ELSE NULL END) AS nsei_close_price
FROM crypto_prices cp
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE strftime('%Y', cp.date) = '2026'
  AND cp.coin_id IN ('bitcoin', 'ethereum', 'tether')
  AND s.Ticker IN ('^GSPC', '^IXIC', '^NSEI')
GROUP BY cp.date
ORDER BY cp.date DESC
LIMIT 30;""",
    "30. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison": """
SELECT
    cp.date,
    cp.price_usd AS bitcoin_price,
    o.Price AS oil_price,
    s.Close AS gspc_close_price
FROM crypto_prices cp
JOIN oil o ON cp.date = DATE(o.Date)
JOIN stocks s ON cp.date = DATE(s.Date)
WHERE cp.coin_id = 'bitcoin'
  AND s.Ticker = '^GSPC'
ORDER BY cp.date DESC
LIMIT 30;"""
}

def get_conn():
    return sqlite3.connect("mydb.db")

st.set_page_config(page_title="Cross-Market Analytics", layout="wide", page_icon="📈")

st.title("💰🛢️📈 Cross-Market Analysis: Crypto, Oil & Stocks")
st.caption("Bitcoin • Ethereum • Tether | WTI Crude Oil | S&P 500 • NASDAQ • NIFTY")

# Verify DB
conn = get_conn()
try:
    count = pd.read_sql("SELECT COUNT(*) as n FROM crypto_prices", conn).iloc[0]["n"]
    st.sidebar.success(f"✅ DB connected — {count} crypto price rows")
except:
    st.error("❌ market.db not found or empty. Run the INSERT cell first!")
    st.stop()
conn.close()

page = st.sidebar.radio("📄 Navigate to", [
    "📊 Page 1: Market Overview",
    "🧠 Page 2: SQL Query Runner",
    "🪙 Page 3: Top 3 Crypto Analysis"
])

# ─────────────────────────────────────────────
# PAGE 1
# ─────────────────────────────────────────────
if page == "📊 Page 1: Market Overview":
    st.header("🔍 Market Overview")

    col1, col2 = st.columns(2)
    with col1:
        start_date = st.date_input("📅 Start Date", value=datetime(2025, 1, 1))
    with col2:
        end_date = st.date_input("📅 End Date", value=datetime(2026, 6, 9))

    s, e = str(start_date), str(end_date)
    conn = get_conn()

    # ── KPI Cards ──
    st.subheader("📌 Average Prices in Selected Period")
    k1, k2, k3, k4 = st.columns(4)

    try:
        val = pd.read_sql(f"SELECT ROUND(AVG(price_usd),2) as v FROM crypto_prices WHERE coin_id='bitcoin' AND date BETWEEN '{s}' AND '{e}'", conn).iloc[0]["v"]
        k1.metric("₿ Bitcoin (USD)", f"${val:, .0f}" if val else "N/A")
    except: k1.metric("Bitcoin", "N/A")

    try:
        val = pd.read_sql(f"SELECT ROUND(AVG(Price),2) as v FROM oil WHERE date BETWEEN '{s}' AND '{e}'", conn).iloc[0]["v"]
        k2.metric("🛢️ Oil (USD/barrel)", f"${val:.2f}" if val else "N/A")
    except: k2.metric("Oil", "N/A")

    try:
        val = pd.read_sql(f"SELECT ROUND(AVG(Close),2) as v FROM stocks WHERE Ticker='^GSPC' AND Date BETWEEN '{s}' AND '{e}'", conn).iloc[0]["v"]
        k3.metric("📊 S&P 500 Close", f"${val:,.2f}" if val else "N/A")
    except: k3.metric("S&P 500", "N/A")

    try:
        val = pd.read_sql(f"SELECT ROUND(AVG(Close),2) as v FROM stocks WHERE Ticker='^NSEI' AND Date BETWEEN '{s}' AND '{e}'", conn).iloc[0]["v"]
        k4.metric("📉 NIFTY Close", f"₹{val:,.2f}" if val else "N/A")
    except: k4.metric("NIFTY", "N/A")

    # ── Daily Snapshot Table ──
    st.subheader("📋 Daily Market Snapshot (BTC + Oil + S&P 500 + NIFTY)")
    try:
        snap = pd.read_sql(f"""
            SELECT cp.date,
                   ROUND(cp.price_usd,2) as btc_usd,
                   ROUND(o.Price,2)  as oil_usd,
                   ROUND(sp.Close,2)     as sp500_close,
                   ROUND(ns.Close,2)     as nifty_close
            FROM crypto_prices cp
            JOIN oil o  ON cp.date = DATE(o.Date)
            JOIN stocks sp ON cp.date = DATE(sp.Date) AND sp.Ticker='^GSPC'
            JOIN stocks ns ON cp.date = DATE(ns.Date) AND ns.Ticker='^NSEI'
            WHERE cp.coin_id='bitcoin'
              AND cp.date BETWEEN '{s}' AND '{e}'
            ORDER BY cp.date DESC
            LIMIT 200
        """, conn)
        st.dataframe(snap, use_container_width=True, height=400)

        # ── Line charts ──
        if not snap.empty:
            st.subheader("📈 Bitcoin Price Trend")
            st.line_chart(snap.set_index("date")["btc_usd"])

            st.subheader("🛢️ Oil Price Trend")
            st.line_chart(snap.set_index("date")["oil_usd"])

            st.subheader("📊 S&P 500 vs NIFTY")
            st.line_chart(snap.set_index("date")[["sp500_close","nifty_close"]])
    except Exception as ex:
        st.warning(f"Snapshot query: {ex}")

    conn.close()

# ─────────────────────────────────────────────
# PAGE 2
# ─────────────────────────────────────────────
elif page == "🧠 Page 2: SQL Query Runner":
    st.header("🧠 SQL Query Runner")
    st.info("Select any predefined query and click **Run Query** to execute it against the SQLite database.")

    query_name = st.selectbox("🔽 Select Query", list(SQL_QUERIES.keys()))

    # Show SQL preview
    with st.expander("🔍 View SQL"):
        st.code(SQL_QUERIES[query_name], language="sql")

    if st.button("▶️ Run Query", type="primary"):
        conn = get_conn()
        try:
            result = pd.read_sql(SQL_QUERIES[query_name], conn)
            st.success(f"✅ Returned {len(result)} row(s)")
            st.dataframe(result, use_container_width=True)

            # Auto line chart if date column present
            if "date" in result.columns and len(result) > 5:
                num_cols = result.select_dtypes(include='number').columns.tolist()
                if num_cols:
                    st.line_chart(result.set_index("date")[num_cols])
        except Exception as e:
            st.error(f"Query error: {e}")
        conn.close()

# ─────────────────────────────────────────────
# PAGE 3
# ─────────────────────────────────────────────
elif page == "🪙 Page 3: Top 3 Crypto Analysis":
    st.header("🪙 Top 3 Cryptocurrency Analysis")

    conn = get_conn()
    try:
        coins = pd.read_sql("SELECT DISTINCT coin_id FROM crypto_prices", conn)["coin_id"].tolist()
    except:
        coins = ["bitcoin", "ethereum", "tether"]

    col1, col2, col3 = st.columns(3)
    with col1:
        selected_coin = st.selectbox("🪙 Select Coin", coins)
    with col2:
        start_date = st.date_input("📅 Start Date", value=datetime(2025, 1, 1), key="p3s")
    with col3:
        end_date = st.date_input("📅 End Date", value=datetime(2026, 6, 9), key="p3e")

    s, e = str(start_date), str(end_date)

    try:
        df_coin = pd.read_sql(f"""
            SELECT date, ROUND(price_usd, 2) as price_usd
            FROM crypto_prices
            WHERE coin_id='{selected_coin}' AND date BETWEEN '{s}' AND '{e}'
            ORDER BY date
        """, conn)

        if not df_coin.empty:
            # KPIs
            c1, c2, c3 = st.columns(3)
            c1.metric("📈 Max Price (USD)", f"${df_coin['price_usd'].max():,.2f}")
            c2.metric("📉 Min Price (USD)", f"${df_coin['price_usd'].min():,.2f}")
            c3.metric("📊 Avg Price (USD)", f"${df_coin['price_usd'].mean():,.2f}")

            st.subheader(f"📈 {selected_coin.capitalize()} Daily Price Trend")
            st.line_chart(df_coin.set_index("date")["price_usd"])

            st.subheader("📋 Daily Price Table")
            st.dataframe(df_coin, use_container_width=True, height=400)
        else:
            st.info("No data for selected date range.")
    except Exception as ex:
        st.error(f"Error: {ex}")

    conn.close()

Writing app.py

In [83]:
!streamlit run /content/app.py &>/content/logs.txt &

In [84]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://balloon-parish-servers-publications.trycloudflare.com